UPDATE public.post_office SET name = 'Adlešiči' WHERE number = 8341;
UPDATE public.post_office SET name = 'Ajdovščina' WHERE number = 5270;
UPDATE public.post_office SET name = 'Ankaran/Ancarano' WHERE number = 6280;
UPDATE public.post_office SET name = 'Apače' WHERE number = 9253;
UPDATE public.post_office SET name = 'Artiče' WHERE number = 8253;
UPDATE public.post_office SET name = 'Begunje na Gorenjskem' WHERE number = 4275;
UPDATE public.post_office SET name = 'Begunje pri Cerknici' WHERE number = 1382;
UPDATE public.post_office SET name = 'Beltinci' WHERE number = 9231;
UPDATE public.post_office SET name = 'Benedikt' WHERE number = 2234;
UPDATE public.post_office SET name = 'Bistrica ob Dravi' WHERE number = 2345;
UPDATE public.post_office SET name = 'Bistrica ob Sotli' WHERE number = 3256;
UPDATE public.post_office SET name = 'Bizeljsko' WHERE number = 8259;
UPDATE public.post_office SET name = 'Blagovica' WHERE number = 1223;
UPDATE public.post_office SET name = 'Blanca' WHERE number = 8283;
UPDATE public.post_office SET name = 'Bled' WHERE number = 4260;
UPDATE public.post_office SET name = 'Blejska Dobrava' WHERE number = 4273;
UPDATE public.post_office SET name = 'Bodonci' WHERE number = 9265;
UPDATE public.post_office SET name = 'Bogojina' WHERE number = 9222;
UPDATE public.post_office SET name = 'Bohinjska Bela' WHERE number = 4263;
UPDATE public.post_office SET name = 'Bohinjska Bistrica' WHERE number = 4264;
UPDATE public.post_office SET name = 'Bohinjsko jezero' WHERE number = 4265;
UPDATE public.post_office SET name = 'Borovnica' WHERE number = 1353;
UPDATE public.post_office SET name = 'Boštanj' WHERE number = 8294;
UPDATE public.post_office SET name = 'Bovec' WHERE number = 5230;
UPDATE public.post_office SET name = 'Branik' WHERE number = 5295;
UPDATE public.post_office SET name = 'Braslovče' WHERE number = 3314;
UPDATE public.post_office SET name = 'Breginj' WHERE number = 5223;
UPDATE public.post_office SET name = 'Brestanica' WHERE number = 8280;
UPDATE public.post_office SET name = 'Bresternica' WHERE number = 2354;
UPDATE public.post_office SET name = 'Brezje' WHERE number = 4243;
UPDATE public.post_office SET name = 'Brezovica pri Ljubljani' WHERE number = 1351;
UPDATE public.post_office SET name = 'Brežice' WHERE number = 8250;
UPDATE public.post_office SET name = 'Brnik - Aerodrom' WHERE number = 4210;
UPDATE public.post_office SET name = 'Brusnice' WHERE number = 8321;
UPDATE public.post_office SET name = 'Buče' WHERE number = 3255;
UPDATE public.post_office SET name = 'Bučka ' WHERE number = 8276;
UPDATE public.post_office SET name = 'Cankova' WHERE number = 9261;
UPDATE public.post_office SET name = 'Celje ' WHERE number = 3000;
UPDATE public.post_office SET name = 'Celje - poštni predali' WHERE number = 3001;
UPDATE public.post_office SET name = 'Cerklje na Gorenjskem' WHERE number = 4207;
UPDATE public.post_office SET name = 'Cerklje ob Krki' WHERE number = 8263;
UPDATE public.post_office SET name = 'Cerknica' WHERE number = 1380;
UPDATE public.post_office SET name = 'Cerkno' WHERE number = 5282;
UPDATE public.post_office SET name = 'Cerkvenjak' WHERE number = 2236;
UPDATE public.post_office SET name = 'Ceršak' WHERE number = 2215;
UPDATE public.post_office SET name = 'Cirkovce' WHERE number = 2326;
UPDATE public.post_office SET name = 'Cirkulane' WHERE number = 2282;
UPDATE public.post_office SET name = 'Col' WHERE number = 5273;
UPDATE public.post_office SET name = 'Čatež ob Savi' WHERE number = 8251;
UPDATE public.post_office SET name = 'Čemšenik' WHERE number = 1413;
UPDATE public.post_office SET name = 'Čepovan' WHERE number = 5253;
UPDATE public.post_office SET name = 'Črenšovci' WHERE number = 9232;
UPDATE public.post_office SET name = 'Črna na Koroškem' WHERE number = 2393;
UPDATE public.post_office SET name = 'Črni Kal' WHERE number = 6275;
UPDATE public.post_office SET name = 'Črni Vrh nad Idrijo' WHERE number = 5274;
UPDATE public.post_office SET name = 'Črniče' WHERE number = 5262;
UPDATE public.post_office SET name = 'Črnomelj' WHERE number = 8340;
UPDATE public.post_office SET name = 'Dekani' WHERE number = 6271;
UPDATE public.post_office SET name = 'Deskle' WHERE number = 5210;
UPDATE public.post_office SET name = 'Destrnik' WHERE number = 2253;
UPDATE public.post_office SET name = 'Divača' WHERE number = 6215;
UPDATE public.post_office SET name = 'Dob' WHERE number = 1233;
UPDATE public.post_office SET name = 'Dobje pri Planini' WHERE number = 3224;
UPDATE public.post_office SET name = 'Dobova' WHERE number = 8257;
UPDATE public.post_office SET name = 'Dobovec' WHERE number = 1423;
UPDATE public.post_office SET name = 'Dobravlje' WHERE number = 5263;
UPDATE public.post_office SET name = 'Dobrna' WHERE number = 3204;
UPDATE public.post_office SET name = 'Dobrnič' WHERE number = 8211;
UPDATE public.post_office SET name = 'Dobrova' WHERE number = 1356;
UPDATE public.post_office SET name = 'Dobrovnik/Dobronak ' WHERE number = 9223;
UPDATE public.post_office SET name = 'Dobrovo v Brdih' WHERE number = 5212;
UPDATE public.post_office SET name = 'Dol pri Hrastniku' WHERE number = 1431;
UPDATE public.post_office SET name = 'Dol pri Ljubljani' WHERE number = 1262;
UPDATE public.post_office SET name = 'Dole pri Litiji' WHERE number = 1273;
UPDATE public.post_office SET name = 'Dolenja vas' WHERE number = 1331;
UPDATE public.post_office SET name = 'Dolenjske Toplice' WHERE number = 8350;
UPDATE public.post_office SET name = 'Domžale' WHERE number = 1230;
UPDATE public.post_office SET name = 'Dornava' WHERE number = 2252;
UPDATE public.post_office SET name = 'Dornberk' WHERE number = 5294;
UPDATE public.post_office SET name = 'Draga' WHERE number = 1319;
UPDATE public.post_office SET name = 'Dragatuš' WHERE number = 8343;
UPDATE public.post_office SET name = 'Dramlje' WHERE number = 3222;
UPDATE public.post_office SET name = 'Dravograd' WHERE number = 2370;
UPDATE public.post_office SET name = 'Duplje' WHERE number = 4203;
UPDATE public.post_office SET name = 'Dutovlje' WHERE number = 6221;
UPDATE public.post_office SET name = 'Dvor' WHERE number = 8361;
UPDATE public.post_office SET name = 'Fala' WHERE number = 2343;
UPDATE public.post_office SET name = 'Fokovci' WHERE number = 9208;
UPDATE public.post_office SET name = 'Fram' WHERE number = 2313;
UPDATE public.post_office SET name = 'Frankolovo' WHERE number = 3213;
UPDATE public.post_office SET name = 'Gabrovka' WHERE number = 1274;
UPDATE public.post_office SET name = 'Globoko' WHERE number = 8254;
UPDATE public.post_office SET name = 'Godovič' WHERE number = 5275;
UPDATE public.post_office SET name = 'Golnik' WHERE number = 4204;
UPDATE public.post_office SET name = 'Gomilsko' WHERE number = 3303;
UPDATE public.post_office SET name = 'Gorenja vas' WHERE number = 4224;
UPDATE public.post_office SET name = 'Gorica pri Slivnici' WHERE number = 3263;
UPDATE public.post_office SET name = 'Gorišnica' WHERE number = 2272;
UPDATE public.post_office SET name = 'Gornja Radgona' WHERE number = 9250;
UPDATE public.post_office SET name = 'Gornji Grad' WHERE number = 3342;
UPDATE public.post_office SET name = 'Gozd Martuljek' WHERE number = 4282;
UPDATE public.post_office SET name = 'Gračišče' WHERE number = 6272;
UPDATE public.post_office SET name = 'Grad' WHERE number = 9264;
UPDATE public.post_office SET name = 'Gradac' WHERE number = 8332;
UPDATE public.post_office SET name = 'Grahovo' WHERE number = 1384;
UPDATE public.post_office SET name = 'Grahovo ob Bači' WHERE number = 5242;
UPDATE public.post_office SET name = 'Grgar' WHERE number = 5251;
UPDATE public.post_office SET name = 'Griže' WHERE number = 3302;
UPDATE public.post_office SET name = 'Grobelno' WHERE number = 3231;
UPDATE public.post_office SET name = 'Grosuplje' WHERE number = 1290;
UPDATE public.post_office SET name = 'Hajdina' WHERE number = 2288;
UPDATE public.post_office SET name = 'Hinje' WHERE number = 8362;
UPDATE public.post_office SET name = 'Hoče' WHERE number = 2311;
UPDATE public.post_office SET name = 'Hodoš/Hodos' WHERE number = 9205;
UPDATE public.post_office SET name = 'Horjul' WHERE number = 1354;
UPDATE public.post_office SET name = 'Hotedršica' WHERE number = 1372;
UPDATE public.post_office SET name = 'Hrastnik' WHERE number = 1430;
UPDATE public.post_office SET name = 'Hruševje' WHERE number = 6225;
UPDATE public.post_office SET name = 'Hrušica' WHERE number = 4276;
UPDATE public.post_office SET name = 'Idrija' WHERE number = 5280;
UPDATE public.post_office SET name = 'Ig' WHERE number = 1292;
UPDATE public.post_office SET name = 'Ilirska Bistrica' WHERE number = 6250;
UPDATE public.post_office SET name = 'Ilirska Bistrica-Trnovo' WHERE number = 6251;
UPDATE public.post_office SET name = 'Ivančna Gorica' WHERE number = 1295;
UPDATE public.post_office SET name = 'Ivanjkovci' WHERE number = 2259;
UPDATE public.post_office SET name = 'Izlake' WHERE number = 1411;
UPDATE public.post_office SET name = 'Izola/Isola' WHERE number = 6310;
UPDATE public.post_office SET name = 'Jakobski Dol' WHERE number = 2222;
UPDATE public.post_office SET name = 'Jarenina' WHERE number = 2221;
UPDATE public.post_office SET name = 'Jelšane' WHERE number = 6254;
UPDATE public.post_office SET name = 'Jesenice' WHERE number = 4270;
UPDATE public.post_office SET name = 'Jesenice na Dolenjskem' WHERE number = 8261;
UPDATE public.post_office SET name = 'Jurklošter' WHERE number = 3273;
UPDATE public.post_office SET name = 'Jurovski Dol' WHERE number = 2223;
UPDATE public.post_office SET name = 'Juršinci' WHERE number = 2256;
UPDATE public.post_office SET name = 'Kal nad Kanalom' WHERE number = 5214;
UPDATE public.post_office SET name = 'Kalobje' WHERE number = 3233;
UPDATE public.post_office SET name = 'Kamna Gorica' WHERE number = 4246;
UPDATE public.post_office SET name = 'Kamnica' WHERE number = 2351;
UPDATE public.post_office SET name = 'Kamnik' WHERE number = 1241;
UPDATE public.post_office SET name = 'Kanal' WHERE number = 5213;
UPDATE public.post_office SET name = 'Kapele' WHERE number = 8258;
UPDATE public.post_office SET name = 'Kapla' WHERE number = 2362;
UPDATE public.post_office SET name = 'Kidričevo' WHERE number = 2325;
UPDATE public.post_office SET name = 'Kisovec' WHERE number = 1412;
UPDATE public.post_office SET name = 'Knežak' WHERE number = 6253;
UPDATE public.post_office SET name = 'Kobarid' WHERE number = 5222;
UPDATE public.post_office SET name = 'Kobilje' WHERE number = 9227;
UPDATE public.post_office SET name = 'Kočevje' WHERE number = 1330;
UPDATE public.post_office SET name = 'Kočevska Reka' WHERE number = 1338;
UPDATE public.post_office SET name = 'Kog' WHERE number = 2276;
UPDATE public.post_office SET name = 'Kojsko' WHERE number = 5211;
UPDATE public.post_office SET name = 'Komen' WHERE number = 6223;
UPDATE public.post_office SET name = 'Komenda' WHERE number = 1218;
UPDATE public.post_office SET name = 'Koper/Capodistria ' WHERE number = 6000;
UPDATE public.post_office SET name = 'Koper/Capodistria - poštni predali' WHERE number = 6001;
UPDATE public.post_office SET name = 'Koprivnica' WHERE number = 8282;
UPDATE public.post_office SET name = 'Kostanjevica na Krasu' WHERE number = 5296;
UPDATE public.post_office SET name = 'Kostanjevica na Krki' WHERE number = 8311;
UPDATE public.post_office SET name = 'Kostel' WHERE number = 1336;
UPDATE public.post_office SET name = 'Košana' WHERE number = 6256;
UPDATE public.post_office SET name = 'Kotlje' WHERE number = 2394;
UPDATE public.post_office SET name = 'Kozina' WHERE number = 6240;
UPDATE public.post_office SET name = 'Kozje' WHERE number = 3260;
UPDATE public.post_office SET name = 'Kranj ' WHERE number = 4000;
UPDATE public.post_office SET name = 'Kranj - poštni predali' WHERE number = 4001;
UPDATE public.post_office SET name = 'Kranjska Gora' WHERE number = 4280;
UPDATE public.post_office SET name = 'Kresnice' WHERE number = 1281;
UPDATE public.post_office SET name = 'Križe' WHERE number = 4294;
UPDATE public.post_office SET name = 'Križevci' WHERE number = 9206;
UPDATE public.post_office SET name = 'Križevci pri Ljutomeru' WHERE number = 9242;
UPDATE public.post_office SET name = 'Krka' WHERE number = 1301;
UPDATE public.post_office SET name = 'Krmelj' WHERE number = 8296;
UPDATE public.post_office SET name = 'Kropa' WHERE number = 4245;
UPDATE public.post_office SET name = 'Krška vas' WHERE number = 8262;
UPDATE public.post_office SET name = 'Krško' WHERE number = 8270;
UPDATE public.post_office SET name = 'Kuzma' WHERE number = 9263;
UPDATE public.post_office SET name = 'Laporje' WHERE number = 2318;
UPDATE public.post_office SET name = 'Laško' WHERE number = 3270;
UPDATE public.post_office SET name = 'Laze v Tuhinju' WHERE number = 1219;
UPDATE public.post_office SET name = 'Lenart v Slovenskih goricah' WHERE number = 2230;
UPDATE public.post_office SET name = 'Lendava/Lendva' WHERE number = 9220;
UPDATE public.post_office SET name = 'Lesce' WHERE number = 4248;
UPDATE public.post_office SET name = 'Lesično' WHERE number = 3261;
UPDATE public.post_office SET name = 'Leskovec pri Krškem' WHERE number = 8273;
UPDATE public.post_office SET name = 'Libeliče' WHERE number = 2372;
UPDATE public.post_office SET name = 'Limbuš' WHERE number = 2341;
UPDATE public.post_office SET name = 'Litija' WHERE number = 1270;
UPDATE public.post_office SET name = 'Ljubečna' WHERE number = 3202;
UPDATE public.post_office SET name = 'Ljubljana ' WHERE number = 1000;
UPDATE public.post_office SET name = 'Ljubljana - poštni predali' WHERE number = 1001;
UPDATE public.post_office SET name = 'Ljubljana - Črnuče' WHERE number = 1231;
UPDATE public.post_office SET name = 'Ljubljana - Dobrunje' WHERE number = 1261;
UPDATE public.post_office SET name = 'Ljubljana - Polje' WHERE number = 1260;
UPDATE public.post_office SET name = 'Ljubljana - Šentvid' WHERE number = 1210;
UPDATE public.post_office SET name = 'Ljubljana - Šmartno' WHERE number = 1211;
UPDATE public.post_office SET name = 'Ljubno ob Savinji' WHERE number = 3333;
UPDATE public.post_office SET name = 'Ljutomer' WHERE number = 9240;
UPDATE public.post_office SET name = 'Loče' WHERE number = 3215;
UPDATE public.post_office SET name = 'Log pod Mangartom' WHERE number = 5231;
UPDATE public.post_office SET name = 'Log pri Brezovici' WHERE number = 1358;
UPDATE public.post_office SET name = 'Logatec' WHERE number = 1370;
UPDATE public.post_office SET name = 'Logatec' WHERE number = 1371;
UPDATE public.post_office SET name = 'Loka pri Zidanem Mostu' WHERE number = 1434;
UPDATE public.post_office SET name = 'Loka pri Žusmu' WHERE number = 3223;
UPDATE public.post_office SET name = 'Lokev' WHERE number = 6219;
UPDATE public.post_office SET name = 'Loški Potok' WHERE number = 1318;
UPDATE public.post_office SET name = 'Lovrenc na Dravskem polju' WHERE number = 2324;
UPDATE public.post_office SET name = 'Lovrenc na Pohorju' WHERE number = 2344;
UPDATE public.post_office SET name = 'Luče' WHERE number = 3334;
UPDATE public.post_office SET name = 'Lukovica' WHERE number = 1225;
UPDATE public.post_office SET name = 'Mačkovci' WHERE number = 9202;
UPDATE public.post_office SET name = 'Majšperk' WHERE number = 2322;
UPDATE public.post_office SET name = 'Makole' WHERE number = 2321;
UPDATE public.post_office SET name = 'Mala Nedelja' WHERE number = 9243;
UPDATE public.post_office SET name = 'Malečnik' WHERE number = 2229;
UPDATE public.post_office SET name = 'Marezige' WHERE number = 6273;
UPDATE public.post_office SET name = 'Maribor ' WHERE number = 2000;
UPDATE public.post_office SET name = 'Maribor - poštni predali' WHERE number = 2001;
UPDATE public.post_office SET name = 'Marjeta na Dravskem polju' WHERE number = 2206;
UPDATE public.post_office SET name = 'Markovci' WHERE number = 2281;
UPDATE public.post_office SET name = 'Martjanci' WHERE number = 9221;
UPDATE public.post_office SET name = 'Materija' WHERE number = 6242;
UPDATE public.post_office SET name = 'Mavčiče' WHERE number = 4211;
UPDATE public.post_office SET name = 'Medvode' WHERE number = 1215;
UPDATE public.post_office SET name = 'Mengeš' WHERE number = 1234;
UPDATE public.post_office SET name = 'Metlika' WHERE number = 8330;
UPDATE public.post_office SET name = 'Mežica' WHERE number = 2392;
UPDATE public.post_office SET name = 'Miklavž na Dravskem polju' WHERE number = 2204;
UPDATE public.post_office SET name = 'Miklavž pri Ormožu' WHERE number = 2275;
UPDATE public.post_office SET name = 'Miren' WHERE number = 5291;
UPDATE public.post_office SET name = 'Mirna' WHERE number = 8233;
UPDATE public.post_office SET name = 'Mirna Peč' WHERE number = 8216;
UPDATE public.post_office SET name = 'Mislinja' WHERE number = 2382;
UPDATE public.post_office SET name = 'Mojstrana' WHERE number = 4281;
UPDATE public.post_office SET name = 'Mokronog' WHERE number = 8230;
UPDATE public.post_office SET name = 'Moravče' WHERE number = 1251;
UPDATE public.post_office SET name = 'Moravske Toplice' WHERE number = 9226;
UPDATE public.post_office SET name = 'Most na Soči' WHERE number = 5216;
UPDATE public.post_office SET name = 'Motnik' WHERE number = 1221;
UPDATE public.post_office SET name = 'Mozirje' WHERE number = 3330;
UPDATE public.post_office SET name = 'Murska Sobota ' WHERE number = 9000;
UPDATE public.post_office SET name = 'Murska Sobota - poštni predali' WHERE number = 9001;
UPDATE public.post_office SET name = 'Muta' WHERE number = 2366;
UPDATE public.post_office SET name = 'Naklo' WHERE number = 4202;
UPDATE public.post_office SET name = 'Nazarje' WHERE number = 3331;
UPDATE public.post_office SET name = 'Notranje Gorice' WHERE number = 1357;
UPDATE public.post_office SET name = 'Nova Cerkev' WHERE number = 3203;
UPDATE public.post_office SET name = 'Nova Gorica ' WHERE number = 5000;
UPDATE public.post_office SET name = 'Nova Gorica - poštni predali' WHERE number = 5001;
UPDATE public.post_office SET name = 'Nova vas' WHERE number = 1385;
UPDATE public.post_office SET name = 'Novo mesto' WHERE number = 8000;
UPDATE public.post_office SET name = 'Novo mesto - poštni predali' WHERE number = 8001;
UPDATE public.post_office SET name = 'Obrov' WHERE number = 6243;
UPDATE public.post_office SET name = 'Odranci' WHERE number = 9233;
UPDATE public.post_office SET name = 'Oplotnica' WHERE number = 2317;
UPDATE public.post_office SET name = 'Orehova vas' WHERE number = 2312;
UPDATE public.post_office SET name = 'Ormož' WHERE number = 2270;
UPDATE public.post_office SET name = 'Ortnek' WHERE number = 1316;
UPDATE public.post_office SET name = 'Osilnica' WHERE number = 1337;
UPDATE public.post_office SET name = 'Otočec' WHERE number = 8222;
UPDATE public.post_office SET name = 'Ožbalt' WHERE number = 2361;
UPDATE public.post_office SET name = 'Pernica' WHERE number = 2231;
UPDATE public.post_office SET name = 'Pesnica pri Mariboru' WHERE number = 2211;
UPDATE public.post_office SET name = 'Petrovci' WHERE number = 9203;
UPDATE public.post_office SET name = 'Petrovče' WHERE number = 3301;
UPDATE public.post_office SET name = 'Piran/Pirano' WHERE number = 6330;
UPDATE public.post_office SET name = 'Pišece' WHERE number = 8255;
UPDATE public.post_office SET name = 'Pivka' WHERE number = 6257;
UPDATE public.post_office SET name = 'Planina' WHERE number = 6232;
UPDATE public.post_office SET name = 'Planina pri Sevnici' WHERE number = 3225;
UPDATE public.post_office SET name = 'Pobegi' WHERE number = 6276;
UPDATE public.post_office SET name = 'Podbočje' WHERE number = 8312;
UPDATE public.post_office SET name = 'Podbrdo' WHERE number = 5243;
UPDATE public.post_office SET name = 'Podčetrtek' WHERE number = 3254;
UPDATE public.post_office SET name = 'Podgorci' WHERE number = 2273;
UPDATE public.post_office SET name = 'Podgorje' WHERE number = 6216;
UPDATE public.post_office SET name = 'Podgorje pri Slovenj Gradcu' WHERE number = 2381;
UPDATE public.post_office SET name = 'Podgrad' WHERE number = 6244;
UPDATE public.post_office SET name = 'Podkum' WHERE number = 1414;
UPDATE public.post_office SET name = 'Podlehnik' WHERE number = 2286;
UPDATE public.post_office SET name = 'Podnanos' WHERE number = 5272;
UPDATE public.post_office SET name = 'Podnart' WHERE number = 4244;
UPDATE public.post_office SET name = 'Podplat' WHERE number = 3241;
UPDATE public.post_office SET name = 'Podsreda' WHERE number = 3257;
UPDATE public.post_office SET name = 'Podvelka' WHERE number = 2363;
UPDATE public.post_office SET name = 'Pohorje' WHERE number = 2208;
UPDATE public.post_office SET name = 'Polenšak' WHERE number = 2257;
UPDATE public.post_office SET name = 'Polhov Gradec' WHERE number = 1355;
UPDATE public.post_office SET name = 'Poljane nad Škofjo Loko' WHERE number = 4223;
UPDATE public.post_office SET name = 'Poljčane' WHERE number = 2319;
UPDATE public.post_office SET name = 'Polšnik' WHERE number = 1272;
UPDATE public.post_office SET name = 'Polzela' WHERE number = 3313;
UPDATE public.post_office SET name = 'Ponikva' WHERE number = 3232;
UPDATE public.post_office SET name = 'Portorož/Portorose' WHERE number = 6320;
UPDATE public.post_office SET name = 'Postojna' WHERE number = 6230;
UPDATE public.post_office SET name = 'Pragersko' WHERE number = 2331;
UPDATE public.post_office SET name = 'Prebold' WHERE number = 3312;
UPDATE public.post_office SET name = 'Preddvor' WHERE number = 4205;
UPDATE public.post_office SET name = 'Prem' WHERE number = 6255;
UPDATE public.post_office SET name = 'Preserje' WHERE number = 1352;
UPDATE public.post_office SET name = 'Prestranek' WHERE number = 6258;
UPDATE public.post_office SET name = 'Prevalje' WHERE number = 2391;
UPDATE public.post_office SET name = 'Prevorje' WHERE number = 3262;
UPDATE public.post_office SET name = 'Primskovo ' WHERE number = 1276;
UPDATE public.post_office SET name = 'Pristava pri Mestinju' WHERE number = 3253;
UPDATE public.post_office SET name = 'Prosenjakovci/Partosfalva' WHERE number = 9207;
UPDATE public.post_office SET name = 'Prvačina' WHERE number = 5297;
UPDATE public.post_office SET name = 'Ptuj' WHERE number = 2250;
UPDATE public.post_office SET name = 'Ptujska Gora' WHERE number = 2323;
UPDATE public.post_office SET name = 'Puconci' WHERE number = 9201;
UPDATE public.post_office SET name = 'Rače' WHERE number = 2327;
UPDATE public.post_office SET name = 'Radeče' WHERE number = 1433;
UPDATE public.post_office SET name = 'Radenci' WHERE number = 9252;
UPDATE public.post_office SET name = 'Radlje ob Dravi' WHERE number = 2360;
UPDATE public.post_office SET name = 'Radomlje' WHERE number = 1235;
UPDATE public.post_office SET name = 'Radovljica' WHERE number = 4240;
UPDATE public.post_office SET name = 'Raka' WHERE number = 8274;
UPDATE public.post_office SET name = 'Rakek' WHERE number = 1381;
UPDATE public.post_office SET name = 'Rateče - Planica' WHERE number = 4283;
UPDATE public.post_office SET name = 'Ravne na Koroškem' WHERE number = 2390;
UPDATE public.post_office SET name = 'Razkrižje' WHERE number = 9246;
UPDATE public.post_office SET name = 'Rečica ob Savinji' WHERE number = 3332;
UPDATE public.post_office SET name = 'Renče' WHERE number = 5292;
UPDATE public.post_office SET name = 'Ribnica' WHERE number = 1310;
UPDATE public.post_office SET name = 'Ribnica na Pohorju' WHERE number = 2364;
UPDATE public.post_office SET name = 'Rimske Toplice' WHERE number = 3272;
UPDATE public.post_office SET name = 'Rob' WHERE number = 1314;
UPDATE public.post_office SET name = 'Ročinj' WHERE number = 5215;
UPDATE public.post_office SET name = 'Rogaška Slatina' WHERE number = 3250;
UPDATE public.post_office SET name = 'Rogašovci' WHERE number = 9262;
UPDATE public.post_office SET name = 'Rogatec' WHERE number = 3252;
UPDATE public.post_office SET name = 'Rovte' WHERE number = 1373;
UPDATE public.post_office SET name = 'Ruše' WHERE number = 2342;
UPDATE public.post_office SET name = 'Sava' WHERE number = 1282;
UPDATE public.post_office SET name = 'Sečovlje/Sicciole' WHERE number = 6333;
UPDATE public.post_office SET name = 'Selca' WHERE number = 4227;
UPDATE public.post_office SET name = 'Selnica ob Dravi' WHERE number = 2352;
UPDATE public.post_office SET name = 'Semič' WHERE number = 8333;
UPDATE public.post_office SET name = 'Senovo' WHERE number = 8281;
UPDATE public.post_office SET name = 'Senožeče' WHERE number = 6224;
UPDATE public.post_office SET name = 'Sevnica' WHERE number = 8290;
UPDATE public.post_office SET name = 'Sežana' WHERE number = 6210;
UPDATE public.post_office SET name = 'Sladki Vrh' WHERE number = 2214;
UPDATE public.post_office SET name = 'Slap ob Idrijci' WHERE number = 5283;
UPDATE public.post_office SET name = 'Slovenj Gradec' WHERE number = 2380;
UPDATE public.post_office SET name = 'Slovenska Bistrica' WHERE number = 2310;
UPDATE public.post_office SET name = 'Slovenske Konjice' WHERE number = 3210;
UPDATE public.post_office SET name = 'Smlednik' WHERE number = 1216;
UPDATE public.post_office SET name = 'Soča' WHERE number = 5232;
UPDATE public.post_office SET name = 'Sodražica' WHERE number = 1317;
UPDATE public.post_office SET name = 'Solčava' WHERE number = 3335;
UPDATE public.post_office SET name = 'Solkan' WHERE number = 5250;
UPDATE public.post_office SET name = 'Sorica' WHERE number = 4229;
UPDATE public.post_office SET name = 'Sovodenj' WHERE number = 4225;
UPDATE public.post_office SET name = 'Spodnja Idrija' WHERE number = 5281;
UPDATE public.post_office SET name = 'Spodnji Duplek' WHERE number = 2241;
UPDATE public.post_office SET name = 'Spodnji Ivanjci' WHERE number = 9245;
UPDATE public.post_office SET name = 'Središče ob Dravi' WHERE number = 2277;
UPDATE public.post_office SET name = 'Srednja vas v Bohinju' WHERE number = 4267;
UPDATE public.post_office SET name = 'Sromlje ' WHERE number = 8256;
UPDATE public.post_office SET name = 'Srpenica' WHERE number = 5224;
UPDATE public.post_office SET name = 'Stahovica' WHERE number = 1242;
UPDATE public.post_office SET name = 'Stara Cerkev' WHERE number = 1332;
UPDATE public.post_office SET name = 'Stari trg ob Kolpi' WHERE number = 8342;
UPDATE public.post_office SET name = 'Stari trg pri Ložu' WHERE number = 1386;
UPDATE public.post_office SET name = 'Starše' WHERE number = 2205;
UPDATE public.post_office SET name = 'Stoperce' WHERE number = 2289;
UPDATE public.post_office SET name = 'Stopiče' WHERE number = 8322;
UPDATE public.post_office SET name = 'Stranice' WHERE number = 3206;
UPDATE public.post_office SET name = 'Straža' WHERE number = 8351;
UPDATE public.post_office SET name = 'Struge' WHERE number = 1313;
UPDATE public.post_office SET name = 'Studenec' WHERE number = 8293;
UPDATE public.post_office SET name = 'Suhor' WHERE number = 8331;
UPDATE public.post_office SET name = 'Sv. Ana v Slovenskih goricah' WHERE number = 2233;
UPDATE public.post_office SET name = 'Sv. Trojica v Slovenskih goricah' WHERE number = 2235;
UPDATE public.post_office SET name = 'Sveti Duh na Ostrem Vrhu' WHERE number = 2353;
UPDATE public.post_office SET name = 'Sveti Jurij ob Ščavnici' WHERE number = 9244;
UPDATE public.post_office SET name = 'Sveti Štefan' WHERE number = 3264;
UPDATE public.post_office SET name = 'Sveti Tomaž' WHERE number = 2258;
UPDATE public.post_office SET name = 'Šalovci' WHERE number = 9204;
UPDATE public.post_office SET name = 'Šempas' WHERE number = 5261;
UPDATE public.post_office SET name = 'Šempeter pri Gorici' WHERE number = 5290;
UPDATE public.post_office SET name = 'Šempeter v Savinjski dolini' WHERE number = 3311;
UPDATE public.post_office SET name = 'Šenčur' WHERE number = 4208;
UPDATE public.post_office SET name = 'Šentilj v Slovenskih goricah' WHERE number = 2212;
UPDATE public.post_office SET name = 'Šentjanž' WHERE number = 8297;
UPDATE public.post_office SET name = 'Šentjanž pri Dravogradu' WHERE number = 2373;
UPDATE public.post_office SET name = 'Šentjernej' WHERE number = 8310;
UPDATE public.post_office SET name = 'Šentjur' WHERE number = 3230;
UPDATE public.post_office SET name = 'Šentrupert' WHERE number = 3271;
UPDATE public.post_office SET name = 'Šentrupert' WHERE number = 8232;
UPDATE public.post_office SET name = 'Šentvid pri Stični' WHERE number = 1296;
UPDATE public.post_office SET name = 'Škocjan' WHERE number = 8275;
UPDATE public.post_office SET name = 'Škofije' WHERE number = 6281;
UPDATE public.post_office SET name = 'Škofja Loka' WHERE number = 4220;
UPDATE public.post_office SET name = 'Škofja vas' WHERE number = 3211;
UPDATE public.post_office SET name = 'Škofljica' WHERE number = 1291;
UPDATE public.post_office SET name = 'Šmarje' WHERE number = 6274;
UPDATE public.post_office SET name = 'Šmarje - Sap' WHERE number = 1293;
UPDATE public.post_office SET name = 'Šmarje pri Jelšah' WHERE number = 3240;
UPDATE public.post_office SET name = 'Šmarješke Toplice' WHERE number = 8220;
UPDATE public.post_office SET name = 'Šmartno na Pohorju' WHERE number = 2315;
UPDATE public.post_office SET name = 'Šmartno ob Dreti' WHERE number = 3341;
UPDATE public.post_office SET name = 'Šmartno ob Paki' WHERE number = 3327;
UPDATE public.post_office SET name = 'Šmartno pri Litiji' WHERE number = 1275;
UPDATE public.post_office SET name = 'Šmartno pri Slovenj Gradcu' WHERE number = 2383;
UPDATE public.post_office SET name = 'Šmartno v Rožni dolini' WHERE number = 3201;
UPDATE public.post_office SET name = 'Šoštanj' WHERE number = 3325;
UPDATE public.post_office SET name = 'Štanjel' WHERE number = 6222;
UPDATE public.post_office SET name = 'Štore' WHERE number = 3220;
UPDATE public.post_office SET name = 'Tabor' WHERE number = 3304;
UPDATE public.post_office SET name = 'Teharje' WHERE number = 3221;
UPDATE public.post_office SET name = 'Tišina' WHERE number = 9251;
UPDATE public.post_office SET name = 'Tolmin' WHERE number = 5220;
UPDATE public.post_office SET name = 'Topolšica' WHERE number = 3326;
UPDATE public.post_office SET name = 'Trbonje' WHERE number = 2371;
UPDATE public.post_office SET name = 'Trbovlje' WHERE number = 1420;
UPDATE public.post_office SET name = 'Trebelno ' WHERE number = 8231;
UPDATE public.post_office SET name = 'Trebnje' WHERE number = 8210;
UPDATE public.post_office SET name = 'Trnovo pri Gorici' WHERE number = 5252;
UPDATE public.post_office SET name = 'Trnovska vas' WHERE number = 2254;
UPDATE public.post_office SET name = 'Trojane' WHERE number = 1222;
UPDATE public.post_office SET name = 'Trzin' WHERE number = 1236;
UPDATE public.post_office SET name = 'Tržič' WHERE number = 4290;
UPDATE public.post_office SET name = 'Tržišče' WHERE number = 8295;
UPDATE public.post_office SET name = 'Turjak' WHERE number = 1311;
UPDATE public.post_office SET name = 'Turnišče' WHERE number = 9224;
UPDATE public.post_office SET name = 'Uršna sela' WHERE number = 8323;
UPDATE public.post_office SET name = 'Vače' WHERE number = 1252;
UPDATE public.post_office SET name = 'Velenje ' WHERE number = 3320;
UPDATE public.post_office SET name = 'Velenje - poštni predali' WHERE number = 3322;
UPDATE public.post_office SET name = 'Velika Loka' WHERE number = 8212;
UPDATE public.post_office SET name = 'Velika Nedelja' WHERE number = 2274;
UPDATE public.post_office SET name = 'Velika Polana' WHERE number = 9225;
UPDATE public.post_office SET name = 'Velike Lašče' WHERE number = 1315;
UPDATE public.post_office SET name = 'Veliki Gaber' WHERE number = 8213;
UPDATE public.post_office SET name = 'Veržej' WHERE number = 9241;
UPDATE public.post_office SET name = 'Videm - Dobrepolje' WHERE number = 1312;
UPDATE public.post_office SET name = 'Videm pri Ptuju' WHERE number = 2284;
UPDATE public.post_office SET name = 'Vinica' WHERE number = 8344;
UPDATE public.post_office SET name = 'Vipava' WHERE number = 5271;
UPDATE public.post_office SET name = 'Visoko' WHERE number = 4212;
UPDATE public.post_office SET name = 'Višnja Gora' WHERE number = 1294;
UPDATE public.post_office SET name = 'Vitanje' WHERE number = 3205;
UPDATE public.post_office SET name = 'Vitomarci' WHERE number = 2255;
UPDATE public.post_office SET name = 'Vodice' WHERE number = 1217;
UPDATE public.post_office SET name = 'Vojnik' WHERE number = 3212;
UPDATE public.post_office SET name = 'Volčja Draga' WHERE number = 5293;
UPDATE public.post_office SET name = 'Voličina' WHERE number = 2232;
UPDATE public.post_office SET name = 'Vransko' WHERE number = 3305;
UPDATE public.post_office SET name = 'Vremski Britof' WHERE number = 6217;
UPDATE public.post_office SET name = 'Vrhnika' WHERE number = 1360;
UPDATE public.post_office SET name = 'Vuhred' WHERE number = 2365;
UPDATE public.post_office SET name = 'Vuzenica' WHERE number = 2367;
UPDATE public.post_office SET name = 'Zabukovje ' WHERE number = 8292;
UPDATE public.post_office SET name = 'Zagorje ob Savi' WHERE number = 1410;
UPDATE public.post_office SET name = 'Zagradec' WHERE number = 1303;
UPDATE public.post_office SET name = 'Zavrč' WHERE number = 2283;
UPDATE public.post_office SET name = 'Zdole ' WHERE number = 8272;
UPDATE public.post_office SET name = 'Zgornja Besnica' WHERE number = 4201;
UPDATE public.post_office SET name = 'Zgornja Korena' WHERE number = 2242;
UPDATE public.post_office SET name = 'Zgornja Kungota' WHERE number = 2201;
UPDATE public.post_office SET name = 'Zgornja Ložnica' WHERE number = 2316;
UPDATE public.post_office SET name = 'Zgornja Polskava' WHERE number = 2314;
UPDATE public.post_office SET name = 'Zgornja Velka' WHERE number = 2213;
UPDATE public.post_office SET name = 'Zgornje Gorje' WHERE number = 4247;
UPDATE public.post_office SET name = 'Zgornje Jezersko' WHERE number = 4206;
UPDATE public.post_office SET name = 'Zgornji Leskovec' WHERE number = 2285;
UPDATE public.post_office SET name = 'Zidani Most' WHERE number = 1432;
UPDATE public.post_office SET name = 'Zreče' WHERE number = 3214;
UPDATE public.post_office SET name = 'Žabnica' WHERE number = 4209;
UPDATE public.post_office SET name = 'Žalec' WHERE number = 3310;
UPDATE public.post_office SET name = 'Železniki' WHERE number = 4228;
UPDATE public.post_office SET name = 'Žetale' WHERE number = 2287;
UPDATE public.post_office SET name = 'Žiri' WHERE number = 4226;
UPDATE public.post_office SET name = 'Žirovnica' WHERE number = 4274;
UPDATE public.post_office SET name = 'Žužemberk' WHERE number = 8360;