UPDATE public.county SET code = 213 WHERE name = 'Ankaran';
UPDATE public.county SET code = 1 WHERE name = 'Ajdovščina';
UPDATE public.county SET code = 195 WHERE name = 'Apače';
UPDATE public.county SET code = 2 WHERE name = 'Beltinci';
UPDATE public.county SET code = 148 WHERE name = 'Benedikt';
UPDATE public.county SET code = 149 WHERE name = 'Bistrica ob Sotli';
UPDATE public.county SET code = 3 WHERE name = 'Bled';
UPDATE public.county SET code = 150 WHERE name = 'Bloke';
UPDATE public.county SET code = 4 WHERE name = 'Bohinj';
UPDATE public.county SET code = 5 WHERE name = 'Borovnica';
UPDATE public.county SET code = 6 WHERE name = 'Bovec';
UPDATE public.county SET code = 151 WHERE name = 'Braslovče';
UPDATE public.county SET code = 7 WHERE name = 'Brda';
UPDATE public.county SET code = 8 WHERE name = 'Brezovica';
UPDATE public.county SET code = 9 WHERE name = 'Brežice';
UPDATE public.county SET code = 152 WHERE name = 'Cankova';
UPDATE public.county SET code = 11 WHERE name = 'Celje';
UPDATE public.county SET code = 12 WHERE name = 'Cerklje na Gorenjskem';
UPDATE public.county SET code = 13 WHERE name = 'Cerknica';
UPDATE public.county SET code = 14 WHERE name = 'Cerkno';
UPDATE public.county SET code = 153 WHERE name = 'Cerkvenjak';
UPDATE public.county SET code = 196 WHERE name = 'Cirkulane';
UPDATE public.county SET code = 15 WHERE name = 'Črenšovci';
UPDATE public.county SET code = 16 WHERE name = 'Črna na Koroškem';
UPDATE public.county SET code = 17 WHERE name = 'Črnomelj';
UPDATE public.county SET code = 18 WHERE name = 'Destrnik';
UPDATE public.county SET code = 19 WHERE name = 'Divača';
UPDATE public.county SET code = 154 WHERE name = 'Dobje';
UPDATE public.county SET code = 20 WHERE name = 'Dobrepolje';
UPDATE public.county SET code = 155 WHERE name = 'Dobrna';
UPDATE public.county SET code = 21 WHERE name = 'Dobrova - Polhov Gradec';
UPDATE public.county SET code = 156 WHERE name = 'Dobrovnik';
UPDATE public.county SET code = 22 WHERE name = 'Dol pri Ljubljani';
UPDATE public.county SET code = 157 WHERE name = 'Dolenjske Toplice';
UPDATE public.county SET code = 23 WHERE name = 'Domžale';
UPDATE public.county SET code = 24 WHERE name = 'Dornava';
UPDATE public.county SET code = 25 WHERE name = 'Dravograd';
UPDATE public.county SET code = 26 WHERE name = 'Duplek';
UPDATE public.county SET code = 27 WHERE name = 'Gorenja vas - Poljane';
UPDATE public.county SET code = 28 WHERE name = 'Gorišnica';
UPDATE public.county SET code = 207 WHERE name = 'Gorje';
UPDATE public.county SET code = 29 WHERE name = 'Gornja Radgona';
UPDATE public.county SET code = 30 WHERE name = 'Gornji Grad';
UPDATE public.county SET code = 31 WHERE name = 'Gornji Petrovci';
UPDATE public.county SET code = 158 WHERE name = 'Grad';
UPDATE public.county SET code = 32 WHERE name = 'Grosuplje';
UPDATE public.county SET code = 159 WHERE name = 'Hajdina';
UPDATE public.county SET code = 160 WHERE name = 'Hoče - Slivnica';
UPDATE public.county SET code = 161 WHERE name = 'Hodoš';
UPDATE public.county SET code = 162 WHERE name = 'Horjul';
UPDATE public.county SET code = 34 WHERE name = 'Hrastnik';
UPDATE public.county SET code = 35 WHERE name = 'Hrpelje - Kozina';
UPDATE public.county SET code = 36 WHERE name = 'Idrija';
UPDATE public.county SET code = 37 WHERE name = 'Ig';
UPDATE public.county SET code = 38 WHERE name = 'Ilirska Bistrica';
UPDATE public.county SET code = 39 WHERE name = 'Ivančna Gorica';
UPDATE public.county SET code = 40 WHERE name = 'Izola';
UPDATE public.county SET code = 41 WHERE name = 'Jesenice';
UPDATE public.county SET code = 163 WHERE name = 'Jezersko';
UPDATE public.county SET code = 42 WHERE name = 'Juršinci';
UPDATE public.county SET code = 43 WHERE name = 'Kamnik';
UPDATE public.county SET code = 44 WHERE name = 'Kanal';
UPDATE public.county SET code = 45 WHERE name = 'Kidričevo';
UPDATE public.county SET code = 46 WHERE name = 'Kobarid';
UPDATE public.county SET code = 47 WHERE name = 'Kobilje';
UPDATE public.county SET code = 48 WHERE name = 'Kočevje';
UPDATE public.county SET code = 49 WHERE name = 'Komen';
UPDATE public.county SET code = 164 WHERE name = 'Komenda';
UPDATE public.county SET code = 50 WHERE name = 'Koper';
UPDATE public.county SET code = 197 WHERE name = 'Kostanjevica na Krki';
UPDATE public.county SET code = 165 WHERE name = 'Kostel';
UPDATE public.county SET code = 51 WHERE name = 'Kozje';
UPDATE public.county SET code = 52 WHERE name = 'Kranj';
UPDATE public.county SET code = 53 WHERE name = 'Kranjska Gora';
UPDATE public.county SET code = 166 WHERE name = 'Križevci';
UPDATE public.county SET code = 54 WHERE name = 'Krško';
UPDATE public.county SET code = 55 WHERE name = 'Kungota';
UPDATE public.county SET code = 56 WHERE name = 'Kuzma';
UPDATE public.county SET code = 57 WHERE name = 'Laško';
UPDATE public.county SET code = 58 WHERE name = 'Lenart';
UPDATE public.county SET code = 59 WHERE name = 'Lendava';
UPDATE public.county SET code = 60 WHERE name = 'Litija';
UPDATE public.county SET code = 61 WHERE name = 'Ljubljana';
UPDATE public.county SET code = 62 WHERE name = 'Ljubno';
UPDATE public.county SET code = 63 WHERE name = 'Ljutomer';
UPDATE public.county SET code = 208 WHERE name = 'Log - Dragomer';
UPDATE public.county SET code = 64 WHERE name = 'Logatec';
UPDATE public.county SET code = 65 WHERE name = 'Loška dolina';
UPDATE public.county SET code = 66 WHERE name = 'Loški Potok';
UPDATE public.county SET code = 167 WHERE name = 'Lovrenc na Pohorju';
UPDATE public.county SET code = 67 WHERE name = 'Luče';
UPDATE public.county SET code = 68 WHERE name = 'Lukovica';
UPDATE public.county SET code = 69 WHERE name = 'Majšperk';
UPDATE public.county SET code = 198 WHERE name = 'Makole';
UPDATE public.county SET code = 70 WHERE name = 'Maribor';
UPDATE public.county SET code = 168 WHERE name = 'Markovci';
UPDATE public.county SET code = 71 WHERE name = 'Medvode';
UPDATE public.county SET code = 72 WHERE name = 'Mengeš';
UPDATE public.county SET code = 73 WHERE name = 'Metlika';
UPDATE public.county SET code = 74 WHERE name = 'Mežica';
UPDATE public.county SET code = 169 WHERE name = 'Miklavž na Dravskem polju';
UPDATE public.county SET code = 75 WHERE name = 'Miren - Kostanjevica';
UPDATE public.county SET code = 212 WHERE name = 'Mirna';
UPDATE public.county SET code = 170 WHERE name = 'Mirna Peč';
UPDATE public.county SET code = 76 WHERE name = 'Mislinja';
UPDATE public.county SET code = 199 WHERE name = 'Mokronog - Trebelno';
UPDATE public.county SET code = 77 WHERE name = 'Moravče';
UPDATE public.county SET code = 78 WHERE name = 'Moravske Toplice';
UPDATE public.county SET code = 79 WHERE name = 'Mozirje';
UPDATE public.county SET code = 80 WHERE name = 'Murska Sobota';
UPDATE public.county SET code = 81 WHERE name = 'Muta';
UPDATE public.county SET code = 82 WHERE name = 'Naklo';
UPDATE public.county SET code = 83 WHERE name = 'Nazarje';
UPDATE public.county SET code = 84 WHERE name = 'Nova Gorica';
UPDATE public.county SET code = 85 WHERE name = 'Novo mesto';
UPDATE public.county SET code = 86 WHERE name = 'Odranci';
UPDATE public.county SET code = 171 WHERE name = 'Oplotnica';
UPDATE public.county SET code = 87 WHERE name = 'Ormož';
UPDATE public.county SET code = 88 WHERE name = 'Osilnica';
UPDATE public.county SET code = 89 WHERE name = 'Pesnica';
UPDATE public.county SET code = 90 WHERE name = 'Piran';
UPDATE public.county SET code = 91 WHERE name = 'Pivka';
UPDATE public.county SET code = 92 WHERE name = 'Podčetrtek';
UPDATE public.county SET code = 172 WHERE name = 'Podlehnik';
UPDATE public.county SET code = 93 WHERE name = 'Podvelka';
UPDATE public.county SET code = 200 WHERE name = 'Poljčane';
UPDATE public.county SET code = 173 WHERE name = 'Polzela';
UPDATE public.county SET code = 94 WHERE name = 'Postojna';
UPDATE public.county SET code = 174 WHERE name = 'Prebold';
UPDATE public.county SET code = 95 WHERE name = 'Preddvor';
UPDATE public.county SET code = 175 WHERE name = 'Prevalje';
UPDATE public.county SET code = 96 WHERE name = 'Ptuj';
UPDATE public.county SET code = 97 WHERE name = 'Puconci';
UPDATE public.county SET code = 98 WHERE name = 'Rače - Fram';
UPDATE public.county SET code = 99 WHERE name = 'Radeče';
UPDATE public.county SET code = 100 WHERE name = 'Radenci';
UPDATE public.county SET code = 101 WHERE name = 'Radlje ob Dravi';
UPDATE public.county SET code = 102 WHERE name = 'Radovljica';
UPDATE public.county SET code = 103 WHERE name = 'Ravne na Koroškem';
UPDATE public.county SET code = 176 WHERE name = 'Razkrižje';
UPDATE public.county SET code = 209 WHERE name = 'Rečica ob Savinji';
UPDATE public.county SET code = 201 WHERE name = 'Renče - Vogrsko';
UPDATE public.county SET code = 104 WHERE name = 'Ribnica';
UPDATE public.county SET code = 177 WHERE name = 'Ribnica na Pohorju';
UPDATE public.county SET code = 106 WHERE name = 'Rogaška Slatina';
UPDATE public.county SET code = 105 WHERE name = 'Rogašovci';
UPDATE public.county SET code = 107 WHERE name = 'Rogatec';
UPDATE public.county SET code = 108 WHERE name = 'Ruše';
UPDATE public.county SET code = 178 WHERE name = 'Selnica ob Dravi';
UPDATE public.county SET code = 109 WHERE name = 'Semič';
UPDATE public.county SET code = 110 WHERE name = 'Sevnica';
UPDATE public.county SET code = 111 WHERE name = 'Sežana';
UPDATE public.county SET code = 112 WHERE name = 'Slovenj Gradec';
UPDATE public.county SET code = 113 WHERE name = 'Slovenska Bistrica';
UPDATE public.county SET code = 114 WHERE name = 'Slovenske Konjice';
UPDATE public.county SET code = 179 WHERE name = 'Sodražica';
UPDATE public.county SET code = 180 WHERE name = 'Solčava';
UPDATE public.county SET code = 202 WHERE name = 'Središče ob Dravi';
UPDATE public.county SET code = 115 WHERE name = 'Starše';
UPDATE public.county SET code = 203 WHERE name = 'Straža';
UPDATE public.county SET code = 204 WHERE name = 'Sv. Trojica v Slov. Goricah';
UPDATE public.county SET code = 181 WHERE name = 'Sveta Ana';
UPDATE public.county SET code = 182 WHERE name = 'Sveti Andraž v Slov. Goricah';
UPDATE public.county SET code = 116 WHERE name = 'Sveti Jurij ob Ščavnici';
UPDATE public.county SET code = 210 WHERE name = 'Sveti Jurij v Slov. Goricah';
UPDATE public.county SET code = 205 WHERE name = 'Sveti Tomaž';
UPDATE public.county SET code = 33 WHERE name = 'Šalovci';
UPDATE public.county SET code = 183 WHERE name = 'Šempeter - Vrtojba';
UPDATE public.county SET code = 117 WHERE name = 'Šenčur';
UPDATE public.county SET code = 118 WHERE name = 'Šentilj';
UPDATE public.county SET code = 119 WHERE name = 'Šentjernej';
UPDATE public.county SET code = 120 WHERE name = 'Šentjur pri Celju';
UPDATE public.county SET code = 211 WHERE name = 'Šentrupert';
UPDATE public.county SET code = 121 WHERE name = 'Škocjan';
UPDATE public.county SET code = 122 WHERE name = 'Škofja Loka';
UPDATE public.county SET code = 123 WHERE name = 'Škofljica';
UPDATE public.county SET code = 124 WHERE name = 'Šmarje pri Jelšah';
UPDATE public.county SET code = 206 WHERE name = 'Šmarješke Toplice';
UPDATE public.county SET code = 125 WHERE name = 'Šmartno ob Paki';
UPDATE public.county SET code = 194 WHERE name = 'Šmartno pri Litiji';
UPDATE public.county SET code = 126 WHERE name = 'Šoštanj';
UPDATE public.county SET code = 127 WHERE name = 'Štore';
UPDATE public.county SET code = 184 WHERE name = 'Tabor';
UPDATE public.county SET code = 10 WHERE name = 'Tišina';
UPDATE public.county SET code = 128 WHERE name = 'Tolmin';
UPDATE public.county SET code = 129 WHERE name = 'Trbovlje';
UPDATE public.county SET code = 130 WHERE name = 'Trebnje';
UPDATE public.county SET code = 185 WHERE name = 'Trnovska vas';
UPDATE public.county SET code = 186 WHERE name = 'Trzin';
UPDATE public.county SET code = 131 WHERE name = 'Tržič';
UPDATE public.county SET code = 132 WHERE name = 'Turnišče';
UPDATE public.county SET code = 133 WHERE name = 'Velenje';
UPDATE public.county SET code = 187 WHERE name = 'Velika Polana';
UPDATE public.county SET code = 134 WHERE name = 'Velike Lašče';
UPDATE public.county SET code = 188 WHERE name = 'Veržej';
UPDATE public.county SET code = 135 WHERE name = 'Videm';
UPDATE public.county SET code = 136 WHERE name = 'Vipava';
UPDATE public.county SET code = 137 WHERE name = 'Vitanje';
UPDATE public.county SET code = 138 WHERE name = 'Vodice';
UPDATE public.county SET code = 139 WHERE name = 'Vojnik';
UPDATE public.county SET code = 189 WHERE name = 'Vransko';
UPDATE public.county SET code = 140 WHERE name = 'Vrhnika';
UPDATE public.county SET code = 141 WHERE name = 'Vuzenica';
UPDATE public.county SET code = 142 WHERE name = 'Zagorje ob Savi';
UPDATE public.county SET code = 143 WHERE name = 'Zavrč';
UPDATE public.county SET code = 144 WHERE name = 'Zreče';
UPDATE public.county SET code = 190 WHERE name = 'Žalec';
UPDATE public.county SET code = 146 WHERE name = 'Železniki';
UPDATE public.county SET code = 191 WHERE name = 'Žetale';
UPDATE public.county SET code = 147 WHERE name = 'Žiri';
UPDATE public.county SET code = 192 WHERE name = 'Žirovnica';
UPDATE public.county SET code = 193 WHERE name = 'Žužemberk';