UPDATE public.country SET name_iso = 'Afghanistan ', name_len2 = 'AF', name_len3 = 'AFG', num_len3 = 4, new_column = null WHERE name_slo = 'Afganistan';
UPDATE public.country SET name_iso = 'Ålland Islands ', name_len2 = 'AX', name_len3 = 'ALA', num_len3 = 248, new_column = null WHERE name_slo = 'Alandski otoki';
UPDATE public.country SET name_iso = 'Albania ', name_len2 = 'AL', name_len3 = 'ALB', num_len3 = 8, new_column = null WHERE name_slo = 'Albanija';
UPDATE public.country SET name_iso = 'Algeria ', name_len2 = 'DZ', name_len3 = 'DZA', num_len3 = 12, new_column = null WHERE name_slo = 'Alžirija';
UPDATE public.country SET name_iso = 'American Samoa ', name_len2 = 'AS', name_len3 = 'ASM', num_len3 = 16, new_column = null WHERE name_slo = 'Ameriška Samoa';
UPDATE public.country SET name_iso = 'Andorra ', name_len2 = 'AD', name_len3 = 'AND', num_len3 = 20, new_column = null WHERE name_slo = 'Andora';
UPDATE public.country SET name_iso = 'Angola ', name_len2 = 'AO', name_len3 = 'AGO', num_len3 = 24, new_column = null WHERE name_slo = 'Angola';
UPDATE public.country SET name_iso = 'Anguilla ', name_len2 = 'AI', name_len3 = 'AIA', num_len3 = 660, new_column = null WHERE name_slo = 'Angvila';
UPDATE public.country SET name_iso = 'Antarctica ', name_len2 = 'AQ', name_len3 = 'ATA', num_len3 = 10, new_column = null WHERE name_slo = 'Antarktika';
UPDATE public.country SET name_iso = 'Antigua and Barbuda ', name_len2 = 'AG', name_len3 = 'ATG', num_len3 = 28, new_column = null WHERE name_slo = 'Antigva in Barbuda';
UPDATE public.country SET name_iso = 'Argentina ', name_len2 = 'AR', name_len3 = 'ARG', num_len3 = 32, new_column = null WHERE name_slo = 'Argenitna';
UPDATE public.country SET name_iso = 'Armenia ', name_len2 = 'AM', name_len3 = 'ARM', num_len3 = 51, new_column = null WHERE name_slo = 'Armenija';
UPDATE public.country SET name_iso = 'Aruba ', name_len2 = 'AW', name_len3 = 'ABW', num_len3 = 533, new_column = null WHERE name_slo = 'Aruba';
UPDATE public.country SET name_iso = 'Australia ', name_len2 = 'AU', name_len3 = 'AUS', num_len3 = 36, new_column = null WHERE name_slo = 'Avstralija';
UPDATE public.country SET name_iso = 'Austria ', name_len2 = 'AT', name_len3 = 'AUT', num_len3 = 40, new_column = null WHERE name_slo = 'Avstrija';
UPDATE public.country SET name_iso = 'Azerbaijan ', name_len2 = 'AZ', name_len3 = 'AZE', num_len3 = 31, new_column = null WHERE name_slo = 'Azerbajdžan';
UPDATE public.country SET name_iso = 'Bahamas ', name_len2 = 'BS', name_len3 = 'BHS', num_len3 = 44, new_column = null WHERE name_slo = 'Bahami';
UPDATE public.country SET name_iso = 'Bahrain ', name_len2 = 'BH', name_len3 = 'BHR', num_len3 = 48, new_column = null WHERE name_slo = 'Bahrajn';
UPDATE public.country SET name_iso = 'Bangladesh ', name_len2 = 'BD', name_len3 = 'BGD', num_len3 = 50, new_column = null WHERE name_slo = 'Bangladeš';
UPDATE public.country SET name_iso = 'Barbados ', name_len2 = 'BB', name_len3 = 'BRB', num_len3 = 52, new_column = null WHERE name_slo = 'Barbados';
UPDATE public.country SET name_iso = 'Belarus ', name_len2 = 'BY', name_len3 = 'BLR', num_len3 = 112, new_column = null WHERE name_slo = 'Belorusija';
UPDATE public.country SET name_iso = 'Belgium ', name_len2 = 'BE', name_len3 = 'BEL', num_len3 = 56, new_column = null WHERE name_slo = 'Belgija';
UPDATE public.country SET name_iso = 'Belize ', name_len2 = 'BZ', name_len3 = 'BLZ', num_len3 = 84, new_column = null WHERE name_slo = 'Belize';
UPDATE public.country SET name_iso = 'Benin ', name_len2 = 'BJ', name_len3 = 'BEN', num_len3 = 204, new_column = null WHERE name_slo = 'Benin';
UPDATE public.country SET name_iso = 'Bermuda ', name_len2 = 'BM', name_len3 = 'BMU', num_len3 = 60, new_column = null WHERE name_slo = 'Bermudi';
UPDATE public.country SET name_iso = 'Bhutan ', name_len2 = 'BT', name_len3 = 'BTN', num_len3 = 64, new_column = null WHERE name_slo = 'Butan';
UPDATE public.country SET name_iso = 'Bolivia, Plurinational State of ', name_len2 = 'BO', name_len3 = 'BOL', num_len3 = 68, new_column = null WHERE name_slo = 'Bolivija';
UPDATE public.country SET name_iso = 'Bonaire, Sint Eustatius and Saba ', name_len2 = 'BQ', name_len3 = 'BES', num_len3 = 535, new_column = null WHERE name_slo = 'Otočje Bonaire, Sv. Eustatij in Saba';
UPDATE public.country SET name_iso = 'Bosnia and Herzegovina ', name_len2 = 'BA', name_len3 = 'BIH', num_len3 = 70, new_column = null WHERE name_slo = 'Bosna in Hercegovina';
UPDATE public.country SET name_iso = 'Botswana ', name_len2 = 'BW', name_len3 = 'BWA', num_len3 = 72, new_column = null WHERE name_slo = 'Bocvana';
UPDATE public.country SET name_iso = 'Bouvet Island ', name_len2 = 'BV', name_len3 = 'BVT', num_len3 = 74, new_column = null WHERE name_slo = 'Bouvetov otok';
UPDATE public.country SET name_iso = 'Brazil ', name_len2 = 'BR', name_len3 = 'BRA', num_len3 = 76, new_column = null WHERE name_slo = 'Brazilija';
UPDATE public.country SET name_iso = 'British Indian Ocean Territory ', name_len2 = 'IO', name_len3 = 'IOT', num_len3 = 86, new_column = null WHERE name_slo = 'Britansko ozemlje v Indijskem oceanu';
UPDATE public.country SET name_iso = 'Brunei Darussalam ', name_len2 = 'BN', name_len3 = 'BRN', num_len3 = 96, new_column = null WHERE name_slo = 'Brunej';
UPDATE public.country SET name_iso = 'Bulgaria ', name_len2 = 'BG', name_len3 = 'BGR', num_len3 = 100, new_column = null WHERE name_slo = 'Bolgarija';
UPDATE public.country SET name_iso = 'Burkina Faso ', name_len2 = 'BF', name_len3 = 'BFA', num_len3 = 854, new_column = null WHERE name_slo = 'Burkina Faso';
UPDATE public.country SET name_iso = 'Burundi ', name_len2 = 'BI', name_len3 = 'BDI', num_len3 = 108, new_column = null WHERE name_slo = 'Burundi ';
UPDATE public.country SET name_iso = 'Cambodia ', name_len2 = 'KH', name_len3 = 'KHM', num_len3 = 116, new_column = null WHERE name_slo = 'Kambodža';
UPDATE public.country SET name_iso = 'Cameroon ', name_len2 = 'CM', name_len3 = 'CMR', num_len3 = 120, new_column = null WHERE name_slo = 'Kamerun';
UPDATE public.country SET name_iso = 'Canada ', name_len2 = 'CA', name_len3 = 'CAN', num_len3 = 124, new_column = null WHERE name_slo = 'Kanada';
UPDATE public.country SET name_iso = 'Cape Verde ', name_len2 = 'CV', name_len3 = 'CPV', num_len3 = 132, new_column = null WHERE name_slo = 'Kapverdski otoki (Zelenortski otoki)';
UPDATE public.country SET name_iso = 'Cayman Islands ', name_len2 = 'KY', name_len3 = 'CYM', num_len3 = 136, new_column = null WHERE name_slo = 'Kajmanski otoki';
UPDATE public.country SET name_iso = 'Central African Republic ', name_len2 = 'CF', name_len3 = 'CAF', num_len3 = 140, new_column = null WHERE name_slo = 'Srednjeafriška republika';
UPDATE public.country SET name_iso = 'Chad ', name_len2 = 'TD', name_len3 = 'TCD', num_len3 = 148, new_column = null WHERE name_slo = 'Čad';
UPDATE public.country SET name_iso = 'Chile ', name_len2 = 'CL', name_len3 = 'CHL', num_len3 = 152, new_column = null WHERE name_slo = 'Čile';
UPDATE public.country SET name_iso = 'China ', name_len2 = 'CN', name_len3 = 'CHN', num_len3 = 156, new_column = null WHERE name_slo = 'Kitajska';
UPDATE public.country SET name_iso = 'Christmas Island ', name_len2 = 'CX', name_len3 = 'CXR', num_len3 = 162, new_column = null WHERE name_slo = 'Božični otok';
UPDATE public.country SET name_iso = 'Cocos (Keeling) Islands ', name_len2 = 'CC', name_len3 = 'CCK', num_len3 = 166, new_column = null WHERE name_slo = 'Kokosovi in Keelingovi otoki';
UPDATE public.country SET name_iso = 'Colombia ', name_len2 = 'CO', name_len3 = 'COL', num_len3 = 170, new_column = null WHERE name_slo = 'Kolumbija';
UPDATE public.country SET name_iso = 'Comoros ', name_len2 = 'KM', name_len3 = 'COM', num_len3 = 174, new_column = null WHERE name_slo = 'Komori';
UPDATE public.country SET name_iso = 'Congo ', name_len2 = 'CG', name_len3 = 'COG', num_len3 = 178, new_column = null WHERE name_slo = 'Kongo';
UPDATE public.country SET name_iso = 'Congo, the Democratic Republic of the ', name_len2 = 'CD', name_len3 = 'COD', num_len3 = 180, new_column = null WHERE name_slo = 'Demokratična republika Kongo';
UPDATE public.country SET name_iso = 'Cook Islands ', name_len2 = 'CK', name_len3 = 'COK', num_len3 = 184, new_column = null WHERE name_slo = 'Cookovi otoki';
UPDATE public.country SET name_iso = 'Costa Rica ', name_len2 = 'CR', name_len3 = 'CRI', num_len3 = 188, new_column = null WHERE name_slo = 'Kostarika';
UPDATE public.country SET name_iso = 'Côte d''Ivoire ', name_len2 = 'CI', name_len3 = 'CIV', num_len3 = 384, new_column = null WHERE name_slo = 'Slonokoščena obala';
UPDATE public.country SET name_iso = 'Croatia ', name_len2 = 'HR', name_len3 = 'HRV', num_len3 = 191, new_column = null WHERE name_slo = 'Hrvaška';
UPDATE public.country SET name_iso = 'Cuba ', name_len2 = 'CU', name_len3 = 'CUB', num_len3 = 192, new_column = null WHERE name_slo = 'Kuba';
UPDATE public.country SET name_iso = 'Curaçao ', name_len2 = 'CW', name_len3 = 'CUW', num_len3 = 531, new_column = null WHERE name_slo = 'Kurasao';
UPDATE public.country SET name_iso = 'Cyprus ', name_len2 = 'CY', name_len3 = 'CYP', num_len3 = 196, new_column = null WHERE name_slo = 'Ciper';
UPDATE public.country SET name_iso = 'Czech Republic ', name_len2 = 'CZ', name_len3 = 'CZE', num_len3 = 203, new_column = null WHERE name_slo = 'Češka';
UPDATE public.country SET name_iso = 'Denmark ', name_len2 = 'DK', name_len3 = 'DNK', num_len3 = 208, new_column = null WHERE name_slo = 'Danska';
UPDATE public.country SET name_iso = 'Djibouti ', name_len2 = 'DJ', name_len3 = 'DJI', num_len3 = 262, new_column = null WHERE name_slo = 'Džibuti';
UPDATE public.country SET name_iso = 'Dominica ', name_len2 = 'DM', name_len3 = 'DMA', num_len3 = 212, new_column = null WHERE name_slo = 'Dominika';
UPDATE public.country SET name_iso = 'Dominican Republic ', name_len2 = 'DO', name_len3 = 'DOM', num_len3 = 214, new_column = null WHERE name_slo = 'Dominikanska republika';
UPDATE public.country SET name_iso = 'Ecuador ', name_len2 = 'EC', name_len3 = 'ECU', num_len3 = 218, new_column = null WHERE name_slo = 'Ekvador';
UPDATE public.country SET name_iso = 'Egypt ', name_len2 = 'EG', name_len3 = 'EGY', num_len3 = 818, new_column = null WHERE name_slo = 'Egipt';
UPDATE public.country SET name_iso = 'El Salvador ', name_len2 = 'SV', name_len3 = 'SLV', num_len3 = 222, new_column = null WHERE name_slo = 'Salvador';
UPDATE public.country SET name_iso = 'Equatorial Guinea ', name_len2 = 'GQ', name_len3 = 'GNQ', num_len3 = 226, new_column = null WHERE name_slo = 'Ekvatorialna Gvineja';
UPDATE public.country SET name_iso = 'Eritrea ', name_len2 = 'ER', name_len3 = 'ERI', num_len3 = 232, new_column = null WHERE name_slo = 'Eritreja';
UPDATE public.country SET name_iso = 'Estonia ', name_len2 = 'EE', name_len3 = 'EST', num_len3 = 233, new_column = null WHERE name_slo = 'Estonija';
UPDATE public.country SET name_iso = 'Ethiopia ', name_len2 = 'ET', name_len3 = 'ETH', num_len3 = 231, new_column = null WHERE name_slo = 'Etiopija';
UPDATE public.country SET name_iso = 'Falkland Islands (Malvinas) ', name_len2 = 'FK', name_len3 = 'FRO', num_len3 = 234, new_column = null WHERE name_slo = 'Falkalndski otoki';
UPDATE public.country SET name_iso = 'Faroe Islands ', name_len2 = 'FO', name_len3 = 'FLK', num_len3 = 238, new_column = null WHERE name_slo = 'Ferski otoki';
UPDATE public.country SET name_iso = 'Fiji ', name_len2 = 'FJ', name_len3 = 'FJI', num_len3 = 242, new_column = null WHERE name_slo = 'Fidži';
UPDATE public.country SET name_iso = 'Finland ', name_len2 = 'FI', name_len3 = 'FIN', num_len3 = 246, new_column = null WHERE name_slo = 'Finska';
UPDATE public.country SET name_iso = 'France ', name_len2 = 'FR', name_len3 = 'FRA', num_len3 = 250, new_column = null WHERE name_slo = 'Francija';
UPDATE public.country SET name_iso = 'French Guiana ', name_len2 = 'GF', name_len3 = 'GUF', num_len3 = 254, new_column = null WHERE name_slo = 'Francoska Gvajana';
UPDATE public.country SET name_iso = 'French Polynesia ', name_len2 = 'PF', name_len3 = 'PYF', num_len3 = 258, new_column = null WHERE name_slo = 'Francoska Polinezija';
UPDATE public.country SET name_iso = 'French Southern Territories ', name_len2 = 'TF', name_len3 = 'ATF', num_len3 = 260, new_column = null WHERE name_slo = 'Francoska južna ozemlja';
UPDATE public.country SET name_iso = 'Gabon ', name_len2 = 'GA', name_len3 = 'GAB', num_len3 = 266, new_column = null WHERE name_slo = 'Gabon';
UPDATE public.country SET name_iso = 'Gambia ', name_len2 = 'GM', name_len3 = 'GMB', num_len3 = 270, new_column = null WHERE name_slo = 'Gambija';
UPDATE public.country SET name_iso = 'Georgia ', name_len2 = 'GE', name_len3 = 'GEO', num_len3 = 268, new_column = null WHERE name_slo = 'Gruzija';
UPDATE public.country SET name_iso = 'Germany ', name_len2 = 'DE', name_len3 = 'DEU', num_len3 = 276, new_column = null WHERE name_slo = 'Nemčija';
UPDATE public.country SET name_iso = 'Ghana ', name_len2 = 'GH', name_len3 = 'GHA', num_len3 = 288, new_column = null WHERE name_slo = 'Gana';
UPDATE public.country SET name_iso = 'Gibraltar ', name_len2 = 'GI', name_len3 = 'GIB', num_len3 = 292, new_column = null WHERE name_slo = 'Gibraltar';
UPDATE public.country SET name_iso = 'Greece ', name_len2 = 'GR', name_len3 = 'GRC', num_len3 = 300, new_column = null WHERE name_slo = 'Grčija';
UPDATE public.country SET name_iso = 'Greenland ', name_len2 = 'GL', name_len3 = 'GRL', num_len3 = 304, new_column = null WHERE name_slo = 'Grenlandija';
UPDATE public.country SET name_iso = 'Grenada ', name_len2 = 'GD', name_len3 = 'GRD', num_len3 = 308, new_column = null WHERE name_slo = 'Grenada';
UPDATE public.country SET name_iso = 'Guadeloupe ', name_len2 = 'GP', name_len3 = 'GLP', num_len3 = 312, new_column = null WHERE name_slo = 'Guadeloupe';
UPDATE public.country SET name_iso = 'Guam ', name_len2 = 'GU', name_len3 = 'GUM', num_len3 = 316, new_column = null WHERE name_slo = 'Guam';
UPDATE public.country SET name_iso = 'Guatemala ', name_len2 = 'GT', name_len3 = 'GTM', num_len3 = 320, new_column = null WHERE name_slo = 'Gvatemala';
UPDATE public.country SET name_iso = 'Guernsey ', name_len2 = 'GG', name_len3 = 'GGY', num_len3 = 831, new_column = null WHERE name_slo = 'Otok Guernsey';
UPDATE public.country SET name_iso = 'Guinea ', name_len2 = 'GN', name_len3 = 'GIN', num_len3 = 324, new_column = null WHERE name_slo = 'Gvineja';
UPDATE public.country SET name_iso = 'Guinea-Bissau ', name_len2 = 'GW', name_len3 = 'GNB', num_len3 = 624, new_column = null WHERE name_slo = 'Gvineja-Bissau';
UPDATE public.country SET name_iso = 'Guyana ', name_len2 = 'GY', name_len3 = 'GUY', num_len3 = 328, new_column = null WHERE name_slo = 'Gvajana';
UPDATE public.country SET name_iso = 'Haiti ', name_len2 = 'HT', name_len3 = 'HTI', num_len3 = 332, new_column = null WHERE name_slo = 'Haiti';
UPDATE public.country SET name_iso = 'Heard Island and McDonald Islands ', name_len2 = 'HM', name_len3 = 'HMD', num_len3 = 334, new_column = null WHERE name_slo = 'Otok Heard in otočje McDonald';
UPDATE public.country SET name_iso = 'Holy See (Vatican City State) ', name_len2 = 'VA', name_len3 = 'VAT', num_len3 = 336, new_column = null WHERE name_slo = 'Vatikan';
UPDATE public.country SET name_iso = 'Honduras ', name_len2 = 'HN', name_len3 = 'HND', num_len3 = 340, new_column = null WHERE name_slo = 'Honduras';
UPDATE public.country SET name_iso = 'Hong Kong ', name_len2 = 'HK', name_len3 = 'HKG', num_len3 = 344, new_column = null WHERE name_slo = 'Hong Kong';
UPDATE public.country SET name_iso = 'Hungary ', name_len2 = 'HU', name_len3 = 'HUN', num_len3 = 348, new_column = null WHERE name_slo = 'Madžarska';
UPDATE public.country SET name_iso = 'Iceland ', name_len2 = 'IS', name_len3 = 'ISL', num_len3 = 352, new_column = null WHERE name_slo = 'Islandija';
UPDATE public.country SET name_iso = 'India ', name_len2 = 'IN', name_len3 = 'IND', num_len3 = 356, new_column = null WHERE name_slo = 'Indija';
UPDATE public.country SET name_iso = 'Indonesia ', name_len2 = 'ID', name_len3 = 'IDN', num_len3 = 360, new_column = null WHERE name_slo = 'Indonezija';
UPDATE public.country SET name_iso = 'Iran, Islamic Republic of ', name_len2 = 'IR', name_len3 = 'IRN', num_len3 = 364, new_column = null WHERE name_slo = 'Iran';
UPDATE public.country SET name_iso = 'Iraq ', name_len2 = 'IQ', name_len3 = 'IRQ', num_len3 = 368, new_column = null WHERE name_slo = 'Irak';
UPDATE public.country SET name_iso = 'Ireland ', name_len2 = 'IE', name_len3 = 'IRL', num_len3 = 372, new_column = null WHERE name_slo = 'Irska';
UPDATE public.country SET name_iso = 'Isle of Man ', name_len2 = 'IM', name_len3 = 'IMN', num_len3 = 833, new_column = null WHERE name_slo = 'Otok Man';
UPDATE public.country SET name_iso = 'Israel ', name_len2 = 'IL', name_len3 = 'ISR', num_len3 = 376, new_column = null WHERE name_slo = 'Izrael';
UPDATE public.country SET name_iso = 'Italy ', name_len2 = 'IT', name_len3 = 'ITA', num_len3 = 380, new_column = null WHERE name_slo = 'Italija';
UPDATE public.country SET name_iso = 'Jamaica ', name_len2 = 'JM', name_len3 = 'JAM', num_len3 = 388, new_column = null WHERE name_slo = 'Jamajka';
UPDATE public.country SET name_iso = 'Japan ', name_len2 = 'JP', name_len3 = 'JPN', num_len3 = 392, new_column = null WHERE name_slo = 'Japonska';
UPDATE public.country SET name_iso = 'Jersey ', name_len2 = 'JE', name_len3 = 'JEY', num_len3 = 832, new_column = null WHERE name_slo = 'Otok Jersey';
UPDATE public.country SET name_iso = 'Jordan ', name_len2 = 'JO', name_len3 = 'JOR', num_len3 = 400, new_column = null WHERE name_slo = 'Jordanija';
UPDATE public.country SET name_iso = 'Kazakhstan ', name_len2 = 'KZ', name_len3 = 'KAZ', num_len3 = 398, new_column = null WHERE name_slo = 'Kazahstan';
UPDATE public.country SET name_iso = 'Kenya ', name_len2 = 'KE', name_len3 = 'KEN', num_len3 = 404, new_column = null WHERE name_slo = 'Kenija';
UPDATE public.country SET name_iso = 'Kiribati ', name_len2 = 'KI', name_len3 = 'KIR', num_len3 = 296, new_column = null WHERE name_slo = 'Kiribati';
UPDATE public.country SET name_iso = 'Korea, Democratic People''s Republic of ', name_len2 = 'KP', name_len3 = 'PRK', num_len3 = 408, new_column = null WHERE name_slo = 'Severna Koreja';
UPDATE public.country SET name_iso = 'Korea, Republic of ', name_len2 = 'KR', name_len3 = 'KOR', num_len3 = 410, new_column = null WHERE name_slo = 'Južna Koreja';
UPDATE public.country SET name_iso = 'Kuwait ', name_len2 = 'KW', name_len3 = 'KWT', num_len3 = 414, new_column = null WHERE name_slo = 'Kuvajt';
UPDATE public.country SET name_iso = 'Kyrgyzstan ', name_len2 = 'KG', name_len3 = 'KGZ', num_len3 = 417, new_column = null WHERE name_slo = 'Kirgizistan (Kirgizija)';
UPDATE public.country SET name_iso = 'Lao People''s Democratic Republic ', name_len2 = 'LA', name_len3 = 'LAO', num_len3 = 418, new_column = null WHERE name_slo = 'Laos';
UPDATE public.country SET name_iso = 'Latvia ', name_len2 = 'LV', name_len3 = 'LVA', num_len3 = 428, new_column = null WHERE name_slo = 'Latvija';
UPDATE public.country SET name_iso = 'Lebanon ', name_len2 = 'LB', name_len3 = 'LBN', num_len3 = 422, new_column = null WHERE name_slo = 'Libanon';
UPDATE public.country SET name_iso = 'Lesotho ', name_len2 = 'LS', name_len3 = 'LSO', num_len3 = 426, new_column = null WHERE name_slo = 'Lesoto';
UPDATE public.country SET name_iso = 'Liberia ', name_len2 = 'LR', name_len3 = 'LBR', num_len3 = 430, new_column = null WHERE name_slo = 'Liberija';
UPDATE public.country SET name_iso = 'Libya ', name_len2 = 'LY', name_len3 = 'LBY', num_len3 = 434, new_column = null WHERE name_slo = 'Libija';
UPDATE public.country SET name_iso = 'Liechtenstein ', name_len2 = 'LI', name_len3 = 'LIE', num_len3 = 438, new_column = null WHERE name_slo = 'Lihtenštajn';
UPDATE public.country SET name_iso = 'Lithuania ', name_len2 = 'LT', name_len3 = 'LTU', num_len3 = 440, new_column = null WHERE name_slo = 'Litva';
UPDATE public.country SET name_iso = 'Luxembourg ', name_len2 = 'LU', name_len3 = 'LUX', num_len3 = 442, new_column = null WHERE name_slo = 'Luksemburg';
UPDATE public.country SET name_iso = 'Macao ', name_len2 = 'MO', name_len3 = 'MAC', num_len3 = 446, new_column = null WHERE name_slo = 'Makao';
UPDATE public.country SET name_iso = 'Macedonia, the former Yugoslav Republic of ', name_len2 = 'MK', name_len3 = 'MKD', num_len3 = 807, new_column = null WHERE name_slo = 'Makedonija';
UPDATE public.country SET name_iso = 'Madagascar ', name_len2 = 'MG', name_len3 = 'MDG', num_len3 = 450, new_column = null WHERE name_slo = 'Madagaskar';
UPDATE public.country SET name_iso = 'Malawi ', name_len2 = 'MW', name_len3 = 'MWI', num_len3 = 454, new_column = null WHERE name_slo = 'Malavi';
UPDATE public.country SET name_iso = 'Malaysia ', name_len2 = 'MY', name_len3 = 'MYS', num_len3 = 458, new_column = null WHERE name_slo = 'Malezija';
UPDATE public.country SET name_iso = 'Maldives ', name_len2 = 'MV', name_len3 = 'MDV', num_len3 = 462, new_column = null WHERE name_slo = 'Maldivi';
UPDATE public.country SET name_iso = 'Mali ', name_len2 = 'ML', name_len3 = 'MLI', num_len3 = 466, new_column = null WHERE name_slo = 'Mali';
UPDATE public.country SET name_iso = 'Malta ', name_len2 = 'MT', name_len3 = 'MLT', num_len3 = 470, new_column = null WHERE name_slo = 'Malta';
UPDATE public.country SET name_iso = 'Marshall Islands ', name_len2 = 'MH', name_len3 = 'MHL', num_len3 = 584, new_column = null WHERE name_slo = 'Maršalovi otoki';
UPDATE public.country SET name_iso = 'Martinique ', name_len2 = 'MQ', name_len3 = 'MTQ', num_len3 = 474, new_column = null WHERE name_slo = 'Martinik';
UPDATE public.country SET name_iso = 'Mauritania ', name_len2 = 'MR', name_len3 = 'MRT', num_len3 = 478, new_column = null WHERE name_slo = 'Mavretanija';
UPDATE public.country SET name_iso = 'Mauritius ', name_len2 = 'MU', name_len3 = 'MUS', num_len3 = 480, new_column = null WHERE name_slo = 'Mauricius (Moris)';
UPDATE public.country SET name_iso = 'Mayotte ', name_len2 = 'YT', name_len3 = 'MYT', num_len3 = 175, new_column = null WHERE name_slo = 'Francoska skupnost Mejot';
UPDATE public.country SET name_iso = 'Mexico ', name_len2 = 'MX', name_len3 = 'MEX', num_len3 = 484, new_column = null WHERE name_slo = 'Mehika';
UPDATE public.country SET name_iso = 'Micronesia, Federated States of ', name_len2 = 'FM', name_len3 = 'FSM', num_len3 = 583, new_column = null WHERE name_slo = 'Mikronezija';
UPDATE public.country SET name_iso = 'Moldova, Republic of ', name_len2 = 'MD', name_len3 = 'MDA', num_len3 = 498, new_column = null WHERE name_slo = 'Moldavija';
UPDATE public.country SET name_iso = 'Monaco ', name_len2 = 'MC', name_len3 = 'MCO', num_len3 = 492, new_column = null WHERE name_slo = 'Monako';
UPDATE public.country SET name_iso = 'Mongolia ', name_len2 = 'MN', name_len3 = 'MNG', num_len3 = 496, new_column = null WHERE name_slo = 'Mongolija';
UPDATE public.country SET name_iso = 'Montenegro ', name_len2 = 'ME', name_len3 = 'MNE', num_len3 = 499, new_column = null WHERE name_slo = 'Črna Gora';
UPDATE public.country SET name_iso = 'Montserrat ', name_len2 = 'MS', name_len3 = 'MSR', num_len3 = 500, new_column = null WHERE name_slo = 'Montserat';
UPDATE public.country SET name_iso = 'Morocco ', name_len2 = 'MA', name_len3 = 'MAR', num_len3 = 504, new_column = null WHERE name_slo = 'Maroko';
UPDATE public.country SET name_iso = 'Mozambique ', name_len2 = 'MZ', name_len3 = 'MOZ', num_len3 = 508, new_column = null WHERE name_slo = 'Mozambik';
UPDATE public.country SET name_iso = 'Myanmar ', name_len2 = 'MM', name_len3 = 'MMR', num_len3 = 104, new_column = null WHERE name_slo = 'Mjanmar';
UPDATE public.country SET name_iso = 'Namibia ', name_len2 = 'NA', name_len3 = 'NAM', num_len3 = 516, new_column = null WHERE name_slo = 'Namibija';
UPDATE public.country SET name_iso = 'Nauru ', name_len2 = 'NR', name_len3 = 'NRU', num_len3 = 520, new_column = null WHERE name_slo = 'Nauru';
UPDATE public.country SET name_iso = 'Nepal ', name_len2 = 'NP', name_len3 = 'NPL', num_len3 = 524, new_column = null WHERE name_slo = 'Nepal';
UPDATE public.country SET name_iso = 'Netherlands ', name_len2 = 'NL', name_len3 = 'NLD', num_len3 = 528, new_column = null WHERE name_slo = 'Nizozemska';
UPDATE public.country SET name_iso = 'New Caledonia ', name_len2 = 'NC', name_len3 = 'NCL', num_len3 = 540, new_column = null WHERE name_slo = 'Nova Kaledonija';
UPDATE public.country SET name_iso = 'New Zealand ', name_len2 = 'NZ', name_len3 = 'NZL', num_len3 = 554, new_column = null WHERE name_slo = 'Nova Zelandija';
UPDATE public.country SET name_iso = 'Nicaragua ', name_len2 = 'NI', name_len3 = 'NIC', num_len3 = 558, new_column = null WHERE name_slo = 'Nikaragva';
UPDATE public.country SET name_iso = 'Niger ', name_len2 = 'NE', name_len3 = 'NER', num_len3 = 562, new_column = null WHERE name_slo = 'Niger ';
UPDATE public.country SET name_iso = 'Nigeria ', name_len2 = 'NG', name_len3 = 'NGA', num_len3 = 566, new_column = null WHERE name_slo = 'Nigerija';
UPDATE public.country SET name_iso = 'Niue ', name_len2 = 'NU', name_len3 = 'NIU', num_len3 = 570, new_column = null WHERE name_slo = 'Niu';
UPDATE public.country SET name_iso = 'Norfolk Island ', name_len2 = 'NF', name_len3 = 'NFK', num_len3 = 574, new_column = null WHERE name_slo = 'Otok Norflok';
UPDATE public.country SET name_iso = 'Northern Mariana Islands ', name_len2 = 'MP', name_len3 = 'MNP', num_len3 = 580, new_column = null WHERE name_slo = 'Severni Marianski otoki';
UPDATE public.country SET name_iso = 'Norway ', name_len2 = 'NO', name_len3 = 'NOR', num_len3 = 578, new_column = null WHERE name_slo = 'Norveška';
UPDATE public.country SET name_iso = 'Oman ', name_len2 = 'OM', name_len3 = 'OMN', num_len3 = 512, new_column = null WHERE name_slo = 'Oman';
UPDATE public.country SET name_iso = 'Pakistan ', name_len2 = 'PK', name_len3 = 'PAK', num_len3 = 586, new_column = null WHERE name_slo = 'Pakistan';
UPDATE public.country SET name_iso = 'Palau ', name_len2 = 'PW', name_len3 = 'PLW', num_len3 = 585, new_column = null WHERE name_slo = 'Palau ';
UPDATE public.country SET name_iso = 'Palestinian Territory, Occupied ', name_len2 = 'PS', name_len3 = 'PSE', num_len3 = 275, new_column = null WHERE name_slo = 'Palestina';
UPDATE public.country SET name_iso = 'Panama ', name_len2 = 'PA', name_len3 = 'PAN', num_len3 = 591, new_column = null WHERE name_slo = 'Panama';
UPDATE public.country SET name_iso = 'Papua New Guinea ', name_len2 = 'PG', name_len3 = 'PNG', num_len3 = 598, new_column = null WHERE name_slo = 'Papua Nova Gvineja';
UPDATE public.country SET name_iso = 'Paraguay ', name_len2 = 'PY', name_len3 = 'PRY', num_len3 = 600, new_column = null WHERE name_slo = 'Paragvaj';
UPDATE public.country SET name_iso = 'Peru ', name_len2 = 'PE', name_len3 = 'PER', num_len3 = 604, new_column = null WHERE name_slo = 'Peru';
UPDATE public.country SET name_iso = 'Philippines ', name_len2 = 'PH', name_len3 = 'PHL', num_len3 = 608, new_column = null WHERE name_slo = 'Filipini';
UPDATE public.country SET name_iso = 'Pitcairn ', name_len2 = 'PN', name_len3 = 'PCN', num_len3 = 612, new_column = null WHERE name_slo = 'Pitcairnovi otoki';
UPDATE public.country SET name_iso = 'Poland ', name_len2 = 'PL', name_len3 = 'POL', num_len3 = 616, new_column = null WHERE name_slo = 'Poljska';
UPDATE public.country SET name_iso = 'Portugal ', name_len2 = 'PT', name_len3 = 'PRT', num_len3 = 620, new_column = null WHERE name_slo = 'Portugalska';
UPDATE public.country SET name_iso = 'Puerto Rico ', name_len2 = 'PR', name_len3 = 'PRI', num_len3 = 630, new_column = null WHERE name_slo = 'Portoriko';
UPDATE public.country SET name_iso = 'Qatar ', name_len2 = 'QA', name_len3 = 'QAT', num_len3 = 634, new_column = null WHERE name_slo = 'Katar';
UPDATE public.country SET name_iso = 'Réunion ', name_len2 = 'RE', name_len3 = 'REU', num_len3 = 638, new_column = null WHERE name_slo = 'Francoska skupnost Reunion';
UPDATE public.country SET name_iso = 'Romania ', name_len2 = 'RO', name_len3 = 'ROU', num_len3 = 642, new_column = null WHERE name_slo = 'Romunija';
UPDATE public.country SET name_iso = 'Russian Federation ', name_len2 = 'RU', name_len3 = 'RUS', num_len3 = 643, new_column = null WHERE name_slo = 'Ruska federacija';
UPDATE public.country SET name_iso = 'Rwanda ', name_len2 = 'RW', name_len3 = 'RWA', num_len3 = 646, new_column = null WHERE name_slo = 'Ruanda';
UPDATE public.country SET name_iso = 'Saint Barthélemy ', name_len2 = 'BL', name_len3 = 'BLM', num_len3 = 652, new_column = null WHERE name_slo = 'Sveti Bartolomej';
UPDATE public.country SET name_iso = 'Saint Helena, Ascension and Tristan da Cunha ', name_len2 = 'SH', name_len3 = 'SHN', num_len3 = 654, new_column = null WHERE name_slo = 'Sveta Helena';
UPDATE public.country SET name_iso = 'Saint Kitts and Nevis ', name_len2 = 'KN', name_len3 = 'KNA', num_len3 = 659, new_column = null WHERE name_slo = 'Sveti Kits in Nevis';
UPDATE public.country SET name_iso = 'Saint Lucia ', name_len2 = 'LC', name_len3 = 'LCA', num_len3 = 662, new_column = null WHERE name_slo = 'Sveta Lucija';
UPDATE public.country SET name_iso = 'Saint Martin (French part) ', name_len2 = 'MF', name_len3 = 'MAF', num_len3 = 663, new_column = null WHERE name_slo = 'Otok svetega Martina';
UPDATE public.country SET name_iso = 'Saint Pierre and Miquelon ', name_len2 = 'PM', name_len3 = 'SPM', num_len3 = 666, new_column = null WHERE name_slo = 'Sveta Pierre in Miquelon';
UPDATE public.country SET name_iso = 'Saint Vincent and the Grenadines ', name_len2 = 'VC', name_len3 = 'VCT', num_len3 = 670, new_column = null WHERE name_slo = 'Sveti Vincent in Grenadini';
UPDATE public.country SET name_iso = 'Samoa ', name_len2 = 'WS', name_len3 = 'WSM', num_len3 = 882, new_column = null WHERE name_slo = 'Samoa';
UPDATE public.country SET name_iso = 'San Marino ', name_len2 = 'SM', name_len3 = 'SMR', num_len3 = 674, new_column = null WHERE name_slo = 'San Marino';
UPDATE public.country SET name_iso = 'Sao Tome and Principe ', name_len2 = 'ST', name_len3 = 'STP', num_len3 = 678, new_column = null WHERE name_slo = 'Sao Tome in Principe';
UPDATE public.country SET name_iso = 'Saudi Arabia ', name_len2 = 'SA', name_len3 = 'SAU', num_len3 = 682, new_column = null WHERE name_slo = 'Savdska Arabija';
UPDATE public.country SET name_iso = 'Senegal ', name_len2 = 'SN', name_len3 = 'SEN', num_len3 = 686, new_column = null WHERE name_slo = 'Senegal';
UPDATE public.country SET name_iso = 'Serbia ', name_len2 = 'RS', name_len3 = 'SRB', num_len3 = 688, new_column = null WHERE name_slo = 'Srbija';
UPDATE public.country SET name_iso = 'Seychelles ', name_len2 = 'SC', name_len3 = 'SYC', num_len3 = 690, new_column = null WHERE name_slo = 'Sejšeli';
UPDATE public.country SET name_iso = 'Sierra Leone ', name_len2 = 'SL', name_len3 = 'SLE', num_len3 = 694, new_column = null WHERE name_slo = 'Siera Leone';
UPDATE public.country SET name_iso = 'Singapore ', name_len2 = 'SG', name_len3 = 'SGP', num_len3 = 702, new_column = null WHERE name_slo = 'Singapur';
UPDATE public.country SET name_iso = 'Sint Maarten (Dutch part) ', name_len2 = 'SX', name_len3 = 'SXM', num_len3 = 534, new_column = null WHERE name_slo = 'Otok svetega.Martina (Nizozemska)';
UPDATE public.country SET name_iso = 'Slovakia ', name_len2 = 'SK', name_len3 = 'SVK', num_len3 = 703, new_column = null WHERE name_slo = 'Slovaška';
UPDATE public.country SET name_iso = 'Slovenia ', name_len2 = 'SI', name_len3 = 'SVN', num_len3 = 705, new_column = null WHERE name_slo = 'Slovenija';
UPDATE public.country SET name_iso = 'Solomon Islands ', name_len2 = 'SB', name_len3 = 'SLB', num_len3 = 90, new_column = null WHERE name_slo = 'Solomonovi otoki';
UPDATE public.country SET name_iso = 'Somalia ', name_len2 = 'SO', name_len3 = 'SOM', num_len3 = 706, new_column = null WHERE name_slo = 'Somalija';
UPDATE public.country SET name_iso = 'South Africa ', name_len2 = 'ZA', name_len3 = 'ZAF', num_len3 = 710, new_column = null WHERE name_slo = 'Južna afrika';
UPDATE public.country SET name_iso = 'South Georgia and the South Sandwich Islands ', name_len2 = 'GS', name_len3 = 'SGS', num_len3 = 239, new_column = null WHERE name_slo = 'Južna Georgia in Južni Sandwichevi otoki';
UPDATE public.country SET name_iso = 'South Sudan ', name_len2 = 'SS', name_len3 = 'SSD', num_len3 = 728, new_column = null WHERE name_slo = 'Južni Sudan';
UPDATE public.country SET name_iso = 'Spain ', name_len2 = 'ES', name_len3 = 'ESP', num_len3 = 724, new_column = null WHERE name_slo = 'Španija';
UPDATE public.country SET name_iso = 'Sri Lanka ', name_len2 = 'LK', name_len3 = 'LKA', num_len3 = 144, new_column = null WHERE name_slo = 'Šri Lanka';
UPDATE public.country SET name_iso = 'Sudan ', name_len2 = 'SD', name_len3 = 'SDN', num_len3 = 729, new_column = null WHERE name_slo = 'Sudan';
UPDATE public.country SET name_iso = 'Suriname ', name_len2 = 'SR', name_len3 = 'SUR', num_len3 = 740, new_column = null WHERE name_slo = 'Surinam';
UPDATE public.country SET name_iso = 'Svalbard and Jan Mayen ', name_len2 = 'SJ', name_len3 = 'SJM', num_len3 = 744, new_column = null WHERE name_slo = 'Svalbard in Jan Majen ';
UPDATE public.country SET name_iso = 'Swaziland ', name_len2 = 'SZ', name_len3 = 'SWZ', num_len3 = 748, new_column = null WHERE name_slo = 'Svazi';
UPDATE public.country SET name_iso = 'Sweden ', name_len2 = 'SE', name_len3 = 'SWE', num_len3 = 752, new_column = null WHERE name_slo = 'Švedska';
UPDATE public.country SET name_iso = 'Switzerland ', name_len2 = 'CH', name_len3 = 'CHE', num_len3 = 756, new_column = null WHERE name_slo = 'Švica';
UPDATE public.country SET name_iso = 'Syrian Arab Republic ', name_len2 = 'SY', name_len3 = 'SYR', num_len3 = 760, new_column = null WHERE name_slo = 'Sirija';
UPDATE public.country SET name_iso = 'Taiwan, Province of China ', name_len2 = 'TW', name_len3 = 'TWN', num_len3 = 158, new_column = null WHERE name_slo = 'Tajvan';
UPDATE public.country SET name_iso = 'Tajikistan ', name_len2 = 'TJ', name_len3 = 'TJK', num_len3 = 762, new_column = null WHERE name_slo = 'Tadžikistan';
UPDATE public.country SET name_iso = 'Tanzania, United Republic of ', name_len2 = 'TZ', name_len3 = 'TZA', num_len3 = 834, new_column = null WHERE name_slo = 'Tanzanija';
UPDATE public.country SET name_iso = 'Thailand ', name_len2 = 'TH', name_len3 = 'THA', num_len3 = 764, new_column = null WHERE name_slo = 'Tajska';
UPDATE public.country SET name_iso = 'Timor-Leste ', name_len2 = 'TL', name_len3 = 'TLS', num_len3 = 626, new_column = null WHERE name_slo = 'Vzhodni Timor';
UPDATE public.country SET name_iso = 'Togo ', name_len2 = 'TG', name_len3 = 'TGO', num_len3 = 768, new_column = null WHERE name_slo = 'Togo';
UPDATE public.country SET name_iso = 'Tokelau ', name_len2 = 'TK', name_len3 = 'TKL', num_len3 = 772, new_column = null WHERE name_slo = 'Tokelau';
UPDATE public.country SET name_iso = 'Tonga ', name_len2 = 'TO', name_len3 = 'TON', num_len3 = 776, new_column = null WHERE name_slo = 'Tonga';
UPDATE public.country SET name_iso = 'Trinidad and Tobago ', name_len2 = 'TT', name_len3 = 'TTO', num_len3 = 780, new_column = null WHERE name_slo = 'Trinidad in Tobago';
UPDATE public.country SET name_iso = 'Tunisia ', name_len2 = 'TN', name_len3 = 'TUN', num_len3 = 788, new_column = null WHERE name_slo = 'Tunizija';
UPDATE public.country SET name_iso = 'Turkey ', name_len2 = 'TR', name_len3 = 'TUR', num_len3 = 792, new_column = null WHERE name_slo = 'Turčija';
UPDATE public.country SET name_iso = 'Turkmenistan ', name_len2 = 'TM', name_len3 = 'TKM', num_len3 = 795, new_column = null WHERE name_slo = 'Turkmenistan';
UPDATE public.country SET name_iso = 'Turks and Caicos Islands ', name_len2 = 'TC', name_len3 = 'TCA', num_len3 = 796, new_column = null WHERE name_slo = 'Tirški in Kajkoški otoki';
UPDATE public.country SET name_iso = 'Tuvalu ', name_len2 = 'TV', name_len3 = 'TUV', num_len3 = 798, new_column = null WHERE name_slo = 'Tuvalu';
UPDATE public.country SET name_iso = 'Uganda ', name_len2 = 'UG', name_len3 = 'UGA', num_len3 = 800, new_column = null WHERE name_slo = 'Uganda';
UPDATE public.country SET name_iso = 'Ukraine ', name_len2 = 'UA', name_len3 = 'UKR', num_len3 = 804, new_column = null WHERE name_slo = 'Ukrajina';
UPDATE public.country SET name_iso = 'United Arab Emirates ', name_len2 = 'AE', name_len3 = 'ARE', num_len3 = 784, new_column = null WHERE name_slo = 'Združeni Arabski Emirati';
UPDATE public.country SET name_iso = 'United Kingdom ', name_len2 = 'GB', name_len3 = 'GBR', num_len3 = 826, new_column = null WHERE name_slo = 'Velika Britanija';
UPDATE public.country SET name_iso = 'United States ', name_len2 = 'US', name_len3 = 'USA', num_len3 = 840, new_column = null WHERE name_slo = 'Združene države Amerike';
UPDATE public.country SET name_iso = 'United States Minor Outlying Islands ', name_len2 = 'UM', name_len3 = 'UMI', num_len3 = 581, new_column = null WHERE name_slo = 'ZDA zunanji otoki';
UPDATE public.country SET name_iso = 'Uruguay ', name_len2 = 'UY', name_len3 = 'URY', num_len3 = 858, new_column = null WHERE name_slo = 'Urugvaj';
UPDATE public.country SET name_iso = 'Uzbekistan ', name_len2 = 'UZ', name_len3 = 'UZB', num_len3 = 860, new_column = null WHERE name_slo = 'Uzbekistan';
UPDATE public.country SET name_iso = 'Vanuatu ', name_len2 = 'VU', name_len3 = 'VUT', num_len3 = 548, new_column = null WHERE name_slo = 'Republika Vanuatu';
UPDATE public.country SET name_iso = 'Venezuela, Bolivarian Republic of ', name_len2 = 'VE', name_len3 = 'VEN', num_len3 = 862, new_column = null WHERE name_slo = 'Venezuela';
UPDATE public.country SET name_iso = 'Viet Nam ', name_len2 = 'VN', name_len3 = 'VNM', num_len3 = 704, new_column = null WHERE name_slo = 'Vietnam';
UPDATE public.country SET name_iso = 'Virgin Islands, British ', name_len2 = 'VG', name_len3 = 'VGB', num_len3 = 92, new_column = null WHERE name_slo = 'Britanski Deviški otoki';
UPDATE public.country SET name_iso = 'Virgin Islands, U.S. ', name_len2 = 'VI', name_len3 = 'VIR', num_len3 = 850, new_column = null WHERE name_slo = 'Ameriški Deviški otoki';
UPDATE public.country SET name_iso = 'Wallis and Futuna ', name_len2 = 'WF', name_len3 = 'WLF', num_len3 = 876, new_column = null WHERE name_slo = 'Otočje Valis in Futuna';
UPDATE public.country SET name_iso = 'Western Sahara ', name_len2 = 'EH', name_len3 = 'ESH', num_len3 = 732, new_column = null WHERE name_slo = 'Zahodna Sahara';
UPDATE public.country SET name_iso = 'Yemen ', name_len2 = 'YE', name_len3 = 'YEM', num_len3 = 887, new_column = null WHERE name_slo = 'Jemen';
UPDATE public.country SET name_iso = 'Zambia ', name_len2 = 'ZM', name_len3 = 'ZMB', num_len3 = 894, new_column = null WHERE name_slo = 'Zambija';
UPDATE public.country SET name_iso = 'Zimbabwe ', name_len2 = 'ZW', name_len3 = 'ZWE', num_len3 = 716, new_column = null WHERE name_slo = 'Zimbabve';